## Numpy의 주요 함수들(1)


In [18]:
# 우선 실행해 주세요
import numpy as np

#### 예제) 

* 중간고사, 학생들의 국영수사과 성적표

| 학생 번호 | 국어 | 영어 | 수학 | 사회 | 과학 |
|  ----   | --- |---| --- | --- | --- |
|0 |80 |92 |70 | 65 | 92 |
|1 |91 |75 |90 | 68 | 85 | 
|2 |86 |76 |42 | 72 | 88 |
|3 |77 |92 |52 | 60 | 80 |
|4 |75 |85 |85 | 92 | 95 |
|5 |96 |90 |95 | 81 | 72 |


* 기말고사, 학생들의 국영수사과 성적표

| 학생 번호 | 국어 | 영어 | 수학 | 사회 | 과학 |
|  ----   | --- |---| --- | --- | --- |
|0 |85 |95 |90 | 66 | 93 |
|1 |93 |70 |80 | 60 | 81 | 
|2 |89 |78 |55 | 75 | 80 |
|3 |80 |94 |59 | 72 | 90 |
|4 |70 |82 |81 | 95 | 72 |
|5 |90 |76 |93 | 82 | 89 |

In [2]:
middle_scores = np.array([
    [80,92,70,65,92],
    [91,75,90,68,85],
    [86,76,42,72,88],
    [77,92,52,60,80],
    [75,85,85,92,95],
    [96,90,95,81,72]
])

final_scores = np.array([
    [85,95,90,66,93],
    [93,70,80,60,81],
    [89,78,55,75,80],
    [80,94,59,72,90],
    [70,82,81,95,72],
    [90,76,93,82,89]
])

scores = np.stack([middle_scores, final_scores])
scores

array([[[80, 92, 70, 65, 92],
        [91, 75, 90, 68, 85],
        [86, 76, 42, 72, 88],
        [77, 92, 52, 60, 80],
        [75, 85, 85, 92, 95],
        [96, 90, 95, 81, 72]],

       [[85, 95, 90, 66, 93],
        [93, 70, 80, 60, 81],
        [89, 78, 55, 75, 80],
        [80, 94, 59, 72, 90],
        [70, 82, 81, 95, 72],
        [90, 76, 93, 82, 89]]])

현재 데이터의 shape는 (2,6,5)로, 

* 첫번째 축 : 중간 / 기말
* 두번째 축 : 학생 번호 
* 세번째 축 : 과목

으로 구성되어 있다.

## 문제 1. 배열 전체에 연산 적용하기
* 모든 점수의 범위가 0~1이 될수 있도록, 전체 점수를 100으로 나누어 주세요 

In [3]:
# 우선 실행해주세요
scores = np.stack([middle_scores, final_scores])
scores

array([[[80, 92, 70, 65, 92],
        [91, 75, 90, 68, 85],
        [86, 76, 42, 72, 88],
        [77, 92, 52, 60, 80],
        [75, 85, 85, 92, 95],
        [96, 90, 95, 81, 72]],

       [[85, 95, 90, 66, 93],
        [93, 70, 80, 60, 81],
        [89, 78, 55, 75, 80],
        [80, 94, 59, 72, 90],
        [70, 82, 81, 95, 72],
        [90, 76, 93, 82, 89]]])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer1`에 담아주세요

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [6]:
from numpy.testing import assert_array_equal

assert 'answer1' in globals(), "결과를 answer1 변수에 담아주세요!, answer1 값을 보고 평가합니다."

A = [[[0.8 , 0.92, 0.7 , 0.65, 0.92],
        [0.91, 0.75, 0.9 , 0.68, 0.85],
        [0.86, 0.76, 0.42, 0.72, 0.88],
        [0.77, 0.92, 0.52, 0.6 , 0.8 ],
        [0.75, 0.85, 0.85, 0.92, 0.95],
        [0.96, 0.9 , 0.95, 0.81, 0.72]],

       [[0.85, 0.95, 0.9 , 0.66, 0.93],
        [0.93, 0.7 , 0.8 , 0.6 , 0.81],
        [0.89, 0.78, 0.55, 0.75, 0.8 ],
        [0.8 , 0.94, 0.59, 0.72, 0.9 ],
        [0.7 , 0.82, 0.81, 0.95, 0.72],
        [0.9 , 0.76, 0.93, 0.82, 0.89]]]

assert_array_equal(A, answer1, 
               err_msg="\n정답은 \n{}\n입니다. 다시 확인해 주세요\n".format(A))

print("정답입니다!!!")

정답입니다!!!


## 문제 2. 같은 크기의 Array 간 사칙연산

* 중간고사와 기말고사의 합산 성적을 학생별/과목별로 구해주세요

정답 >>> 
```
[[165, 187, 160, 131, 185],
[184, 145, 170, 128, 166],
[175, 154,  97, 147, 168],
[157, 186, 111, 132, 170],
[145, 167, 166, 187, 167],
[186, 166, 188, 163, 161]]
```

In [7]:
# 우선 실행해주세요
scores = np.stack([middle_scores, final_scores])
scores

array([[[80, 92, 70, 65, 92],
        [91, 75, 90, 68, 85],
        [86, 76, 42, 72, 88],
        [77, 92, 52, 60, 80],
        [75, 85, 85, 92, 95],
        [96, 90, 95, 81, 72]],

       [[85, 95, 90, 66, 93],
        [93, 70, 80, 60, 81],
        [89, 78, 55, 75, 80],
        [80, 94, 59, 72, 90],
        [70, 82, 81, 95, 72],
        [90, 76, 93, 82, 89]]])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer2`에 담아주세요

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [9]:
from numpy.testing import assert_array_equal

assert 'answer2' in globals(), "결과를 answer2 변수에 담아주세요!, answer2 값을 보고 평가합니다."

A = [[165, 187, 160, 131, 185],
[184, 145, 170, 128, 166],
[175, 154,  97, 147, 168],
[157, 186, 111, 132, 170],
[145, 167, 166, 187, 167],
[186, 166, 188, 163, 161]]

assert_array_equal(A, answer2,"\n\n정답은 \n{}\n입니다. 다시 확인해 주세요".format(A))
print("정답입니다!!!")

정답입니다!!!


## 3. 다른 크기의 Array 간 사칙연산

* 각 과목별로 가중치가 다르다. 가중치 행렬은 아래와 같고, 가중치를 적용한 점수를 구해봅시다.


| 국어 | 영어 | 수학 | 사회 | 과학 |
|---|---|---|---| ---|
| 0.3 | 0.2 | 0.5 | 0.2 | 0.2 |

In [10]:
# 우선 실행해주세요
scores = np.stack([middle_scores, final_scores])
weights = np.array([0.3,0.2,0.5,0.2,0.2]) # 가중치 행렬
scores, weights

(array([[[80, 92, 70, 65, 92],
         [91, 75, 90, 68, 85],
         [86, 76, 42, 72, 88],
         [77, 92, 52, 60, 80],
         [75, 85, 85, 92, 95],
         [96, 90, 95, 81, 72]],
 
        [[85, 95, 90, 66, 93],
         [93, 70, 80, 60, 81],
         [89, 78, 55, 75, 80],
         [80, 94, 59, 72, 90],
         [70, 82, 81, 95, 72],
         [90, 76, 93, 82, 89]]]), array([0.3, 0.2, 0.5, 0.2, 0.2]))

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer3`에 담아주세요

array([[[24. , 18.4, 35. , 13. , 18.4],
        [27.3, 15. , 45. , 13.6, 17. ],
        [25.8, 15.2, 21. , 14.4, 17.6],
        [23.1, 18.4, 26. , 12. , 16. ],
        [22.5, 17. , 42.5, 18.4, 19. ],
        [28.8, 18. , 47.5, 16.2, 14.4]],

       [[25.5, 19. , 45. , 13.2, 18.6],
        [27.9, 14. , 40. , 12. , 16.2],
        [26.7, 15.6, 27.5, 15. , 16. ],
        [24. , 18.8, 29.5, 14.4, 18. ],
        [21. , 16.4, 40.5, 19. , 14.4],
        [27. , 15.2, 46.5, 16.4, 17.8]]])

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [13]:
from numpy.testing import assert_almost_equal

assert 'answer3' in globals(), "결과를 answer3 변수에 담아주세요!, answer3 값을 보고 평가합니다."

A = [[[24. , 18.4, 35. , 13. , 18.4],
        [27.3, 15. , 45. , 13.6, 17. ],
        [25.8, 15.2, 21. , 14.4, 17.6],
        [23.1, 18.4, 26. , 12. , 16. ],
        [22.5, 17. , 42.5, 18.4, 19. ],
        [28.8, 18. , 47.5, 16.2, 14.4]],

       [[25.5, 19. , 45. , 13.2, 18.6],
        [27.9, 14. , 40. , 12. , 16.2],
        [26.7, 15.6, 27.5, 15. , 16. ],
        [24. , 18.8, 29.5, 14.4, 18. ],
        [21. , 16.4, 40.5, 19. , 14.4],
        [27. , 15.2, 46.5, 16.4, 17.8]]]

assert_almost_equal(A, answer3,decimal=3,err_msg="\n\n정답은 \n{}\n입니다. 다시 확인해 주세요".format(A))
print("정답입니다!!!")

정답입니다!!!


## 4. 이 외에도 다양한 연산 함수들

* 좌표계에는 크게 2가지가 있는데, 하나는 우리가 흔히 쓰는 X,Y축으로 표현되는 직교 좌표계이고. 다른 하나는 각도와 거리로 표현되는 극 좌표계가 있습니다. 직교좌표계에서 극좌표계로 바꾸기 위해서는 아래와 같이 풀면 됩니다.

![](https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Polar_to_cartesian.svg/460px-Polar_to_cartesian.svg.png)

$$x = r*cos\varphi \\ y = r*sin\varphi$$

아래와 같이 극좌표값이 주어졌을 때, 이를 직교좌표값으로 변환해주세요.

| $r$ | $\varphi$ |
|----|----|
| 1  | 0.1 |
| 1  | 0.5 |
| 2  | 0.7 |
| 2  | 1.2 |
| 3  | 1.5 |
| 3  | 2.0 |
| 4  | 2.8 |
| 4  | 3.1 |

In [14]:
# 우선 실행해주세요
coords = np.array([
    [1,0.1],
    [1,0.5],
    [2,0.7],
    [2,1.2],
    [3,1.5],
    [3,2.0],
    [4,2.8],
    [4,3.1]
])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer4`에 담아주세요

array([[ 0.99500417,  0.09983342],
       [ 0.87758256,  0.47942554],
       [ 1.52968437,  1.28843537],
       [ 0.72471551,  1.86407817],
       [ 0.21221161,  2.99248496],
       [-1.24844051,  2.72789228],
       [-3.76888936,  1.3399526 ],
       [-3.9965406 ,  0.16632265]])

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [16]:
from numpy.testing import assert_array_almost_equal

assert 'answer4' in globals(), "결과를 answer4 변수에 담아주세요!, answer4 값을 보고 평가합니다."

A = [[ 0.99500417,  0.09983342],
       [ 0.87758256,  0.47942554],
       [ 1.52968437,  1.28843537],
       [ 0.72471551,  1.86407817],
       [ 0.21221161,  2.99248496],
       [-1.24844051,  2.72789228],
       [-3.76888936,  1.3399526 ],
       [-3.9965406 ,  0.16632265]]

assert_array_almost_equal(A,answer4,decimal=2,
                          err_msg="\n\n정답은 \n{}\n입니다. 다시 확인해 주세요".format(A))

print("정답입니다!!!")

정답입니다!!!


#  

<hr>
<div style = "background-image: url('https://algorithmai.io/static/media/logo.665798c4.png');background-repeat: no-repeat; background-position: right; background-size: 220px 40px; padding : 5px 10px 5px 5px;">
    Copyright(c) 2019 by Public AI. All rights reserved.<br>
    Writen by PAI, SangJae Kang ( rocketgrowthsj@publicai.co.kr )  last updated on 2019/02/21
</div>
<hr>