## Numpy의 주요 함수들(2)


In [1]:
# 우선 실행해 주세요
import numpy as np

#### 예제) 

* 중간고사, 학생들의 국영수사과 성적표

| 학생 번호 | 국어 | 영어 | 수학 | 사회 | 과학 |
|  ----   | --- |---| --- | --- | --- |
|0 |80 |92 |70 | 65 | 92 |
|1 |91 |75 |90 | 68 | 85 | 
|2 |86 |76 |42 | 72 | 88 |
|3 |77 |92 |52 | 60 | 80 |
|4 |75 |85 |85 | 92 | 95 |
|5 |96 |90 |95 | 81 | 72 |


* 기말고사, 학생들의 국영수사과 성적표

| 학생 번호 | 국어 | 영어 | 수학 | 사회 | 과학 |
|  ----   | --- |---| --- | --- | --- |
|0 |85 |95 |90 | 66 | 93 |
|1 |93 |70 |80 | 60 | 81 | 
|2 |89 |78 |55 | 75 | 80 |
|3 |80 |94 |59 | 72 | 90 |
|4 |70 |82 |81 | 95 | 72 |
|5 |90 |76 |93 | 82 | 89 |

In [2]:
middle_scores = np.array([
    [80,92,70,65,92],
    [91,75,90,68,85],
    [86,76,42,72,88],
    [77,92,52,60,80],
    [75,85,85,92,95],
    [96,90,95,81,72]
])

final_scores = np.array([
    [85,95,90,66,93],
    [93,70,80,60,81],
    [89,78,55,75,80],
    [80,94,59,72,90],
    [70,82,81,95,72],
    [90,76,93,82,89]
])

scores = np.stack([middle_scores,final_scores])

scores

array([[[80, 92, 70, 65, 92],
        [91, 75, 90, 68, 85],
        [86, 76, 42, 72, 88],
        [77, 92, 52, 60, 80],
        [75, 85, 85, 92, 95],
        [96, 90, 95, 81, 72]],

       [[85, 95, 90, 66, 93],
        [93, 70, 80, 60, 81],
        [89, 78, 55, 75, 80],
        [80, 94, 59, 72, 90],
        [70, 82, 81, 95, 72],
        [90, 76, 93, 82, 89]]])

현재 데이터의 shape는 (2,6,5)로, 

* 첫번째 축 : 중간 / 기말
* 두번째 축 : 학생 번호 
* 세번째 축 : 과목

으로 구성되어 있다.

## 문제 1. 평균 구하기(1)
* **중간고사** 때, **국어, 영어, 수학** 의 학생 평균 성적은 계산해 주세요.

정답 >>> 
```python
[84.16666667, 85.        , 72.33333333] # [국어, 영어, 수학]
```

In [3]:
# 우선 실행해주세요
scores = np.stack([middle_scores, final_scores])
scores

array([[[80, 92, 70, 65, 92],
        [91, 75, 90, 68, 85],
        [86, 76, 42, 72, 88],
        [77, 92, 52, 60, 80],
        [75, 85, 85, 92, 95],
        [96, 90, 95, 81, 72]],

       [[85, 95, 90, 66, 93],
        [93, 70, 80, 60, 81],
        [89, 78, 55, 75, 80],
        [80, 94, 59, 72, 90],
        [70, 82, 81, 95, 72],
        [90, 76, 93, 82, 89]]])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer1`에 담아주세요

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [5]:
from numpy.testing import assert_almost_equal

assert 'answer1' in globals(), "결과를 answer1 변수에 담아주세요!, answer1 값을 보고 평가합니다."

A = [84.16666667, 85. , 72.33333333]

assert_almost_equal(A, answer1,decimal=0.3,
               err_msg="\n정답은 \n{}\n입니다. 다시 확인해 주세요\n".format(A))

print("정답입니다!!!")

정답입니다!!!


## 문제 2. 차이의 평균 구하기
* **중간고사** 대비 **기말고사** 때의 성적 차이를 구하고, 과목 별 성적 차이의 평균을 구해 주세요!

정답 >>>

```python
[0.33333333, -2.5, 4., 2., -1.16666667] # [국어,영어,수학,사회,과학]
```

In [6]:
# 우선 실행해주세요
scores = np.stack([middle_scores, final_scores])
scores

array([[[80, 92, 70, 65, 92],
        [91, 75, 90, 68, 85],
        [86, 76, 42, 72, 88],
        [77, 92, 52, 60, 80],
        [75, 85, 85, 92, 95],
        [96, 90, 95, 81, 72]],

       [[85, 95, 90, 66, 93],
        [93, 70, 80, 60, 81],
        [89, 78, 55, 75, 80],
        [80, 94, 59, 72, 90],
        [70, 82, 81, 95, 72],
        [90, 76, 93, 82, 89]]])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer2`에 담아주세요

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [9]:
from numpy.testing import assert_almost_equal

assert 'answer2' in globals(), "결과를 answer2 변수에 담아주세요!, answer2 값을 보고 평가합니다."

A = [ 0.333, -2.5 ,4. ,  2. , -1.16666]

assert_almost_equal(A, answer2,decimal=3,
                    err_msg="\n\n정답은 \n{}\n입니다. 다시 확인해 주세요".format(A))
print("정답입니다!!!")

정답입니다!!!


## 문제 3. 표준 점수 구하기
* 표준 점수는 아래와 같은 수식을 따른다. **중간고사** 때의 성적을 표준점수로 환산해 주세요

$$
z = \frac{x-\mu}{\sigma}
$$


주의사항 
* 과목 별로 평균과 표준편차를 따로 구해 적용해야 합니다.


정답 >>>

```python
# 표준점수로 환산한 결과는 아래처럼 나옵니다
[[-0.55121733,  0.9834151 , -0.11852496, -0.74926865,  0.87121368],
       [ 0.90399642, -1.40487872,  0.89740324, -0.46829291, -0.04356068],
       [ 0.24253563, -1.26439085, -1.54082442, -0.09365858,  0.34848547],
       [-0.94809381,  0.9834151 , -1.03286033, -1.21756156, -0.69697095],
       [-1.21267813,  0.        ,  0.64342119,  1.77951304,  1.26325984],
       [ 1.56545722,  0.70243936,  1.15138528,  0.74926865, -1.74242737]]
```

In [10]:
# 우선 실행해주세요
middle_scores

array([[80, 92, 70, 65, 92],
       [91, 75, 90, 68, 85],
       [86, 76, 42, 72, 88],
       [77, 92, 52, 60, 80],
       [75, 85, 85, 92, 95],
       [96, 90, 95, 81, 72]])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer3`에 담아주세요

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [12]:
from numpy.testing import assert_almost_equal

assert 'answer3' in globals(), "결과를 answer3 변수에 담아주세요!, answer3 값을 보고 평가합니다."

A = [[-0.55121733,  0.9834151 , -0.11852496, -0.74926865,  0.87121368],
       [ 0.90399642, -1.40487872,  0.89740324, -0.46829291, -0.04356068],
       [ 0.24253563, -1.26439085, -1.54082442, -0.09365858,  0.34848547],
       [-0.94809381,  0.9834151 , -1.03286033, -1.21756156, -0.69697095],
       [-1.21267813,  0.        ,  0.64342119,  1.77951304,  1.26325984],
       [ 1.56545722,  0.70243936,  1.15138528,  0.74926865, -1.74242737]]

assert_almost_equal(A, answer3,decimal=3,err_msg="\n\n정답은 \n{}\n입니다. 다시 확인해 주세요".format(A))
print("정답입니다!!!")

정답입니다!!!


#  

<hr>
<div style = "background-image: url('https://algorithmai.io/static/media/logo.665798c4.png');background-repeat: no-repeat; background-position: right; background-size: 220px 40px; padding : 5px 10px 5px 5px;">
    Copyright(c) 2019 by Public AI. All rights reserved.<br>
    Writen by PAI, SangJae Kang ( rocketgrowthsj@publicai.co.kr )  last updated on 2019/02/21
</div>
<hr>