## Tensor을 다루는 함수들

In [1]:
%matplotlib inline
import numpy as np
import tensorflow as tf 
import matplotlib.pyplot as plt
import pandas as pd

tf.enable_eager_execution()
np.set_printoptions(formatter={
    'float_kind': lambda x: "{0:0.3f}".format(x)})

## 예제 데이터 )  califonia housing price

MedInc : 행정 구역 내 소득의 중앙값<br>
HouseAge : 행정 구역 내 주택 연식의 중앙값<br>
AveRooms : 평균 방 갯수<br>
AveBedrms : 평균 침실 갯수<br>
Population : 행정 구역 내 인구 수<br>
AveOccup : 평균 자가 비율<br>
Latitude : 해당 행정 구역의 위도<br>
Longitude : 해당 행정 구역의 경도<br>

In [2]:
from sklearn.datasets import fetch_california_housing
california = fetch_california_housing()

clf_data = california.data

df = pd.DataFrame(california.data,columns=california.feature_names)
df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

## 문제 1. 평균 보다 큰 값의 갯수 세기

+ 각 열의 평균보다 큰 값의 갯수를 출력해 보세요. <br>

In [3]:
# 우선 실행해주세요
tf_data = tf.constant(df.values)
tf_data

<tf.Tensor: id=0, shape=(20640, 8), dtype=float64, numpy=
array([[8.325, 41.000, 6.984, ..., 2.556, 37.880, -122.230],
       [8.301, 21.000, 6.238, ..., 2.110, 37.860, -122.220],
       [7.257, 52.000, 8.288, ..., 2.802, 37.850, -122.240],
       ...,
       [1.700, 17.000, 5.206, ..., 2.326, 39.430, -121.220],
       [1.867, 18.000, 5.330, ..., 2.123, 39.430, -121.320],
       [2.389, 16.000, 5.255, ..., 2.617, 39.370, -121.240]])>

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer1`에 담아주세요

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [13]:
from numpy.testing import assert_array_equal

assert 'answer1' in globals(), "결과를 answer1 변수에 담아주세요!, answer1 값을 보고 평가합니다."

A = df[df>df.mean()].count().values

if "numpy" in dir(answer1):
    answer1 = answer1.numpy()

assert_array_equal(A, answer1,"\n\n정답은 \n{}\n입니다. 다시 확인해 주세요".format(A))
print("정답입니다!!!")

정답입니다!!!


## 문제 2. HouseAge가 20년 이상의 데이터 가져오기

* HouseAge(2번째 열)가 20보다 크거나 같은 데이터들을 가져와 주세요

In [6]:
# 우선 실행해주세요
tf_data = tf.constant(df.values)
tf_data

<tf.Tensor: id=9, shape=(20640, 8), dtype=float64, numpy=
array([[8.325, 41.000, 6.984, ..., 2.556, 37.880, -122.230],
       [8.301, 21.000, 6.238, ..., 2.110, 37.860, -122.220],
       [7.257, 52.000, 8.288, ..., 2.802, 37.850, -122.240],
       ...,
       [1.700, 17.000, 5.206, ..., 2.326, 39.430, -121.220],
       [1.867, 18.000, 5.330, ..., 2.123, 39.430, -121.320],
       [2.389, 16.000, 5.255, ..., 2.617, 39.370, -121.240]])>

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer2`에 담아주세요

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [8]:
from numpy.testing import assert_array_equal

assert 'answer2' in globals(), "결과를 answer2 변수에 담아주세요!"

A = df[df.HouseAge>=20].values

if "numpy" in dir(answer2):
    answer2 = answer2.numpy()

assert_array_equal(A, answer2,
                   "\n\n정답은 \n{}\n입니다. 다시 확인해 주세요".format(A))
print("정답입니다!!!")

정답입니다!!!


## 문제 3. HouseAge가 50년 이상의 행 인덱스 가져오기
* HouseAge(2번째 열)가 50보다 크거나 같은 데이터의 인덱스를 가져와 주세요

In [9]:
# 우선 실행해주세요
tf_data = tf.constant(df.values)
tf_data

<tf.Tensor: id=45, shape=(20640, 8), dtype=float64, numpy=
array([[8.325, 41.000, 6.984, ..., 2.556, 37.880, -122.230],
       [8.301, 21.000, 6.238, ..., 2.110, 37.860, -122.220],
       [7.257, 52.000, 8.288, ..., 2.802, 37.850, -122.240],
       ...,
       [1.700, 17.000, 5.206, ..., 2.326, 39.430, -121.220],
       [1.867, 18.000, 5.330, ..., 2.123, 39.430, -121.320],
       [2.389, 16.000, 5.255, ..., 2.617, 39.370, -121.240]])>

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer3`에 담아주세요

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [11]:
from numpy.testing import assert_array_equal

assert 'answer3' in globals(), "결과를 answer3 변수에 담아주세요!"

A = np.where(df.HouseAge>=50)[0]

if "numpy" in dir(answer3):
    answer3 = answer3.numpy()

assert_array_equal(A, answer3.ravel(),
                   "\n\n정답은 \n{}\n입니다. 다시 확인해 주세요".format(A))
print("정답입니다!!!")

정답입니다!!!


#  

<hr>
<div style = "background-image: url('https://algorithmai.io/static/media/logo.665798c4.png');background-repeat: no-repeat; background-position: right; background-size: 220px 40px; padding : 5px 10px 5px 5px;">
    Copyright(c) 2019 by Public AI. All rights reserved.<br>
    Writen by PAI, SangJae Kang ( rocketgrowthsj@publicai.co.kr )  last updated on 2019/02/21
</div>
<hr>