 ╔══<i><b>Alai-DeepLearning</b></i>════════════════════════════╗
###  &nbsp;&nbsp; **✎&nbsp;&nbsp;Week 2. Numpy Basis**
# Section 1. Numpy의 필요성


### _Objective_
1. 파이썬의 Numpy를 파이썬의 List와 비교하며 Numpy만의 주요한 특징들을 익힙니다.<br>
2. 다양한 예제를 통해 Numpy를 직접 사용해보고, 그 활용을 이해합니다.<br>

  
╚═════════════════════════════════════════╝


In [0]:
# Numpy Package를 호출합니다. (Numpy는 주로 np로 aliasing 됩니다.)
import numpy as np

# \[ 1. List VS Numpy \]

----

----

> *Python의 list와 numpy를 비교해보면서, Numpy가 왜 보편적으로 쓰이는 지 배워봅시다.*

### 예제 데이터 ) **중간고사, 학생들의 국영수 성적표**

┌─<i> ✍︎ Example  </i>──────────────────────────────┐ <br>

&nbsp;&nbsp;&nbsp;&nbsp;학생들의 성적표를 List와 Numpy로 각각 저장하여 다양하게 활용해보겠습니다.<br>

└─────────────────────────────────────┘<br>

`scores_list`<br>
`scores_np`

| 학생 번호 | 국어 | 영어 | 수학 | 
|  ----   | --- |---| --- |
|0 |80 |92 |70 |
|1 |91 |75 |90|
|2 |86 |76 |42 |
|3 |77 |92 |52 |
|4 |75 |85 |85 | 
|5 |96 |90 |95 |

> ***위의 성적표는 파이썬으로 정리하면 아래와 같이 정의할 수 있습니다.***

In [0]:
# list로 표현된 학생들의 성적표
scores_list = [
    [80, 92, 70],
    [91, 75, 90],
    [86, 96, 42],
    [77, 92, 52],
    [75, 85, 85],
    [96, 90, 95]
]

# np.array로 표현된 학생들의 성적표
scores_np = np.array([
    [80, 92, 70],
    [91, 75, 90],
    [86, 96, 42],
    [77, 92, 52],
    [75, 85, 85],
    [96, 90, 95]
])

<br>

## 1. List와 Numpy의 Indexing 비교하기

<hr>

+ List와 Numpy를 통해 저장된 요소들을 불러오는 코드를 비교하여 그 차이를 살펴보겠습니다.

┌───────────────────────────────────┐ <br>

### &nbsp;&nbsp; 예제 1) 1번째 학생의 성적 가져오기

#### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;⓵ `list`로 가져오기

In [0]:
scores_list[1]

[91, 75, 90]

#### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ⓶ `np.array`로 가져오기 

In [0]:
scores_np[1]

array([91, 75, 90])

###  

└───────────────────────────────────┘<br>

┌───────────────────────────────────┐ <br>
###  &nbsp;&nbsp; 예제 2) 1번부터 3번까지의 학생 성적 가져오기

#### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;⓵ `list`로 가져오기

In [0]:
scores_list[1:4]

[[91, 75, 90], [86, 96, 42], [77, 92, 52]]

#### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ⓶ `np.array`로 가져오기 

In [0]:
scores_np[1:4]

array([[91, 75, 90],
       [86, 96, 42],
       [77, 92, 52]])

###  

└───────────────────────────────────┘<br>

┌───────────────────────────────────┐ <br>

### &nbsp;&nbsp; 예제 3) 0번, 4번,5번의 학생 성적 가져오기

#### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;⓵ `list`로 가져오기

In [0]:
scores_list[[0,4,5]] # 불가능

>> *위와 같은 방식으로는 `list`에선 가져올 수 없습니다.*

In [0]:
[scores_list[0],scores_list[4],scores_list[5]]

[[80, 92, 70], [75, 85, 85], [96, 90, 95]]

#### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ⓶ `np.array`로 가져오기 

In [0]:
scores_np[[0,4,5]] # 훨씬 더 간단하게 가져올 수 있다.

array([[80, 92, 70],
       [75, 85, 85],
       [96, 90, 95]])

###  

└───────────────────────────────────┘<br>

┌───────────────────────────────────┐ <br>

### &nbsp;&nbsp; 예제 4) 모든 학생들의 국어 성적 가져오기

#### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;⓵ `list`로 가져오기

In [0]:
language_scores = []

for score in scores_list:
    language_scores.append(score[0])

language_scores

[80, 91, 86, 77, 75, 96]

#### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ⓶ `np.array`로 가져오기 

In [0]:
scores_np[:,0] 

array([80, 91, 86, 77, 75, 96])

###  

└───────────────────────────────────┘<br>

<br>

## 2. List와 Numpy의 집계연산 비교하기

<hr>

+ 집계연산이란, 여러개의 값을 하나의 값으로 결과를 내는 연산을 의미합니다.
+ 예를들어, 여러 요소들의 합을 구하거나, 평균을 구하거나, 요소의 개수를 세거나, 요소들의 그룹별 최소값을 찾는 연산이 집계연산에 해당합니다. 
+ List와 Numpy를 통해 저장된 Data들의 집계연산 코드를 비교해보겠습니다.

┌───────────────────────────────────┐ <br>

### &nbsp;&nbsp; 예제 5) 중간고사 학생별 전과목 점수 총합

#### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;⓵ `list`로 가져오기

In [0]:
total_scores = []

for score in scores_list:
    total_score = sum(score) # 리스트 내 원소들의 총합 더하기
    total_scores.append(total_score) 
    
total_scores

[242, 256, 224, 221, 245, 281]

#### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ⓶ `np.array`로 가져오기 

In [0]:
scores_np.sum(axis=1)# 한줄로 작성할 수 있다.

array([242, 256, 224, 221, 245, 281])

###  

└───────────────────────────────────┘<br>

┌───────────────────────────────────┐ <br>
### &nbsp;&nbsp;예제 6) 중간고사 과목별 평균 성적

#### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;⓵ `list`로 가져오기

In [0]:
total_language_score = 0
total_math_score = 0
total_english_score = 0

for score in scores_list:
    total_language_score = total_language_score + score[0]
    total_math_score = total_math_score + score[1]
    total_english_score = total_english_score + score[2]
    
avg_language_score = total_language_score / len(scores_list)
avg_math_score = total_math_score / len(scores_list)
avg_english_score = total_english_score / len(scores_list)

[avg_language_score, avg_math_score, avg_english_score]

[84.16666666666667, 88.33333333333333, 72.33333333333333]

#### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ⓶ `np.array`로 가져오기 


In [0]:
scores_np.mean(axis=0)# 한줄로 작성할 수 있다.

array([84.16666667, 88.33333333, 72.33333333])

###  

└───────────────────────────────────┘<br>

<br>

## 3. 각 요소별 연산 적용하기

<hr>

+ List나 array를 다룰때면, 각각의 요소별로 연산을 적용해야할 때가 있습니다.
+ List와 np.array의 경우, 각 요소별 연산 적용하는 방법을 알아보겠습니다.

┌───────────────────────────────────┐ <br>
### &nbsp;&nbsp;예제 7) 학생들이 만점 대비 각각 몇점씩 틀렸는지 표로 만들기

#### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;⓵ `list`로 가져오기

In [0]:
miss_scores = []

for scores in scores_list:
    miss_score = []
    for score in scores:
        miss = 100-score # 100점 대비 몇점 틀렸는지 계산
        miss_score.append(miss)
    miss_scores.append(miss_score)
miss_scores

[[20, 8, 30], [9, 25, 10], [14, 4, 58], [23, 8, 48], [25, 15, 15], [4, 10, 5]]

#### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ⓶ `np.array`로 가져오기 


In [0]:
100 - scores_np

array([[20,  8, 30],
       [ 9, 25, 10],
       [14,  4, 58],
       [23,  8, 48],
       [25, 15, 15],
       [ 4, 10,  5]])

###  

└───────────────────────────────────┘<br>

┌───────────────────────────────────┐ <br>
### 예제 8) 중간고사 대비 기말고사 성적 변동 표 만들기

In [0]:
# list로 표현된 학생들의 기말고사 성적표
final_scores_list = [
    [85, 95, 72],
    [93, 60, 95],
    [80, 90, 70],
    [80, 94, 56],
    [77, 82, 80],
    [90, 95, 90]
]

# np.array로 표현된 학생들의 기말고사 성적표
final_scores_np = np.array([
    [85, 95, 72],
    [93, 60, 95],
    [80, 90, 70],
    [80, 94, 56],
    [77, 82, 80],
    [90, 95, 90]
])

#### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;⓵ `list`로 가져오기

In [0]:
diff_scores = [] # 전체 성적 변동을 담는 리스트
for mid_scores, final_scores in zip(scores_list, final_scores_list):
    diff_score = [] # 학생 별 성적 변동을 담는 리스트
    for mid_score, final_score in zip(mid_scores, final_scores):
        diff = final_score - mid_score
        diff_score.append(diff)
    diff_scores.append(diff_score)
diff_scores

[[5, 3, 2], [2, -15, 5], [-6, -6, 28], [3, 2, 4], [2, -3, -5], [-6, 5, -5]]

#### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ⓶ `np.array`로 가져오기 


In [0]:
final_scores_np - scores_np

array([[  5,   3,   2],
       [  2, -15,   5],
       [ -6,  -6,  28],
       [  3,   2,   4],
       [  2,  -3,  -5],
       [ -6,   5,  -5]])

###  

└───────────────────────────────────┘<br>

#  

---

    Copyright(c) 2019 by Public AI. All rights reserved.
    Writen by PAI, SangJae Kang ( rocketgrowthsj@publicai.co.kr )  last updated on 2019/03/04

---