 ╔══<i><b>Alai-DeepLearning</b></i>═════════════════════════╗
###  &nbsp;&nbsp; **✎&nbsp;&nbsp;Week 2. Numpy Basis**
# Section 3. Numpy의 indexing 과 합치기


### _Objective_
1. numpy array에서 값에 접근하는 방식인 indexing에 대해 배워봅니다 <br>
2. numpy array을 합치거나 쌓는 방식인 stack & concatenate에 대해 배워봅니다. <br>

╚══════════════════════════════════════╝

In [1]:
import numpy as np

## 예제 데이터 ) 중간고사, 학생들의 국영수사과 성적표

┌─<i> ✍︎ Example  </i>──────────────────────────────────────────────────────────────────┐ <br>

&nbsp;&nbsp;&nbsp;&nbsp;학생들의 국영수사과 성적표를 Numpy Array로 저장한 후 다양하게 활용해보겠습니다.<br>


| 학생 번호 | 국어 | 영어 | 수학 | 사회 | 과학 |
|  ----   | --- |---| --- | --- | --- |
|0 |80 |92 |70 | 65 | 92 |
|1 |91 |75 |90 | 68 | 85 | 
|2 |86 |76 |42 | 72 | 88 |
|3 |77 |92 |52 | 60 | 80 |
|4 |75 |85 |85 | 92 | 95 |
|5 |96 |90 |95 | 81 | 72 |

In [2]:
scores = np.array([
    [80,92,70,65,92],
    [91,75,90,68,85],
    [86,76,42,72,88],
    [77,92,52,60,80],
    [75,85,85,92,95],
    [96,90,95,81,72]
])
scores

array([[80, 92, 70, 65, 92],
       [91, 75, 90, 68, 85],
       [86, 76, 42, 72, 88],
       [77, 92, 52, 60, 80],
       [75, 85, 85, 92, 95],
       [96, 90, 95, 81, 72]])

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *예제를 통해 어떤식으로 값을 가져올 수 있는지 파악해봅시다.*

##  

└─────────────────────────────────────────────────────────────────────────┘<br>

<br><br>

# \[ 1. Numpy의 Indexing \]

----

----

> *`np.array`는 다양한 방법으로 내부의 값을 가져올 수 있습니다.*<br>
> *예제를 통해 다양한 형태를 배워봅시다.*

#### **데이터 ) 중간고사, 학생들의 국영수사과 성적표**

| 학생 번호 | 국어 | 영어 | 수학 | 사회 | 과학 |
|  ----   | --- |---| --- | --- | --- |
|0 |80 |92 |70 | 65 | 92 |
|1 |91 |75 |90 | 68 | 85 | 
|2 |86 |76 |42 | 72 | 88 |
|3 |77 |92 |52 | 60 | 80 |
|4 |75 |85 |85 | 92 | 95 |
|5 |96 |90 |95 | 81 | 72 |



<br>

## 1. 특정 위치의 원소 또는 축 가져오기

---

+ 우리는 원하는 위치값(Index)을 가지고 해당 위치에 있는 원소의 값을 가져오거나
+ 축을 기준으로 원하는 위치의 행 또는 열을 Numpy Array 형태로 가져올 수 있습니다.



### (1) 특정 위치의 원소 가져오기

indexing 의 \[ , \]에서 <br>
&nbsp;&nbsp; \- 첫번째 값은 "행의 Index"<br>
&nbsp;&nbsp; \- 두번째 값은 "열의 Index"<br>
을 의미합니다.

⓵ 학생 번호 2번의 국어 성적을 가져오기

In [3]:
scores[2,0] # 국어의 열 index = 0

86

<br>
⓶ 학생 번호 3번의 수학 성적을 가져오기

In [4]:
scores[3,2] # 수학의 열 index = 2

52

### (2) 특정 행 가져오기 

⓵ 학생 번호 1번의 전체 성적 가져오기

In [5]:
scores[1]

array([91, 75, 90, 68, 85])

In [6]:
scores[1,:] # 위는 아래와 동일합니다. 

array([91, 75, 90, 68, 85])

여기서, : 는 "전부"를 의미합니다. 

### (3) 특정 열 가져오기 

⓵ 전체 국어 성적 가져오기

In [7]:
scores[:,0] # 전체 국어 성적.  

array([80, 91, 86, 77, 75, 96])

<br>

## 2. 특정 범위만 가져오기

---

* `np.array`는 특정 부분을 범위로 지정해서 가져올 수 있습니다.

### (1) slice 방식으로 가져오기

 ⓵ 학생 번호 1번부터 4번까지의 전 과목 성적 가져오기

In [8]:
scores[1:5] # 1<=학생번호<4 까지의 값을 가져올 수 있음

array([[91, 75, 90, 68, 85],
       [86, 76, 42, 72, 88],
       [77, 92, 52, 60, 80],
       [75, 85, 85, 92, 95]])

<br><br>
⓶  홀수 번째 학생의 전 과목 성적 가져오기

In [9]:
scores[1:6:2] # 1,3,5 식으로 학생 번호를 지칭

array([[91, 75, 90, 68, 85],
       [77, 92, 52, 60, 80],
       [96, 90, 95, 81, 72]])

In [10]:
scores[1::2] # 끝까지 지칭하는 경우, 끝값(6)은 생략 가능

array([[91, 75, 90, 68, 85],
       [77, 92, 52, 60, 80],
       [96, 90, 95, 81, 72]])

<br><br>
⓷ 전체 학생의 국영수 성적만 가져오기

In [11]:
scores[:,0:3] # 열 방향도 동일한 방식으로 지정할 수 있음

array([[80, 92, 70],
       [91, 75, 90],
       [86, 76, 42],
       [77, 92, 52],
       [75, 85, 85],
       [96, 90, 95]])

In [12]:
scores[:,:3] # 시작이 0인 경우 생략 가능

array([[80, 92, 70],
       [91, 75, 90],
       [86, 76, 42],
       [77, 92, 52],
       [75, 85, 85],
       [96, 90, 95]])

<br><br>

### (2) list 방식으로 가져오기

⓵ 학생 번호 1번, 3번, 4번의  전 과목 성적 가져오기

In [13]:
scores[[1,3,4]] # 직접 학생 번호들을 list에 담아서 지칭할 수 있음

array([[91, 75, 90, 68, 85],
       [77, 92, 52, 60, 80],
       [75, 85, 85, 92, 95]])

<br><br>
⓶ 수학과 과학의 전 과목 성적 가져오기

In [14]:
scores[:,[2,4]] 

array([[70, 92],
       [90, 85],
       [42, 88],
       [52, 80],
       [85, 95],
       [95, 72]])

In [15]:
scores[:,[4,2]] # 꼭 오름차순으로 가져올 필요 없이, 순서를 바꿀 수 있다. 

array([[92, 70],
       [85, 90],
       [88, 42],
       [80, 52],
       [95, 85],
       [72, 95]])

### (3) 조건문으로 가져오기

`np.array`는 조건문으로 특정값을 만족하는 index만 가져올 수 있습니다.

#### Numpy에서의 비교 연산자

> np.array에 비교 연산자를 지정하면 모든 원소 별로 True, False 값을 반환합니다.

In [16]:
language_score = scores[:,0]
language_score

array([80, 91, 86, 77, 75, 96])

In [17]:
language_score > 80 # 각 원소별로 80보다 큰지 비교를 합니다.

array([False,  True,  True, False, False,  True])

In [18]:
language_score < 95 # 각 원소별로 95보다 작은지 비교를 합니다.

array([ True,  True,  True,  True,  True, False])

In [19]:
# 두 조건문을 둘다 만족하는 경우는 & 연산자로 표현할 수 있습니다.
(language_score > 80) & (language_score < 95) 

array([False,  True,  True, False, False, False])

In [20]:
# 두 조건문 중 하나라도 만족하는 경우는 | 연산자로 표현할 수 있습니다.
(language_score > 80) | (language_score < 95)

array([ True,  True,  True,  True,  True,  True])

#### Numpy에서의 Where 연산자

> np.array에서 조건에 맞는 원소의 위치를 알고 싶으면 where을 이용하면 됩니다.

In [21]:
np.where(language_score > 80)

(array([1, 2, 5]),)

where 메소드는 조건에 따라 값을 치환할 수 있습니다. `np.where(condition, [x, y])`로, 2번째 인자와 3번째 인자에 값이 입력되면, 조건에 맞는 경우 2번째 인자의 값으로, 조건에 안맞으면 3번째 인자의 값으로 대체됩니다.

In [22]:
np.where(language_score > 80, "합격","불합격")

array(['불합격', '합격', '합격', '불합격', '불합격', '합격'], dtype='<U3')

<br>
⓵ 국어 성적이 80점이 넘는 학생들의 성적을 가져오기



In [23]:
language_score = scores[:,0]
scores[language_score > 80]

array([[91, 75, 90, 68, 85],
       [86, 76, 42, 72, 88],
       [96, 90, 95, 81, 72]])

<br><br>
⓶ 수학 및 과학 성적 모두 80점이 넘는 학생들의 성적 가져오기

In [24]:
math_score = scores[:,2]
science_score = scores[:,4]

In [25]:
scores[(math_score>80) & (science_score>80)]

array([[91, 75, 90, 68, 85],
       [75, 85, 85, 92, 95]])

# \[ 2. Numpy의 Array를 합치는 방식(concatenate,stack) \]

----

----

> *`np.array`에 데이터를 추가하고, 합치고, 쌓는 방식인 concatenate, stack에 대해 배워봅니다. *

<br>
## 1. np.concatenate()

---

* np.concatenate()는 특정 축 방향으로 데이터를 추가할 때 쓰입니다.

#### **데이터 ) 중간고사, 학생들의 국영수사과 성적표**

| 학생 번호 | 국어 | 영어 | 수학 | 사회 | 과학 |
|  ----   | --- |---| --- | --- | --- |
|0 |80 |92 |70 | 65 | 92 |
|1 |91 |75 |90 | 68 | 85 | 
|2 |86 |76 |42 | 72 | 88 |
|3 |77 |92 |52 | 60 | 80 |
|4 |75 |85 |85 | 92 | 95 |
|5 |96 |90 |95 | 81 | 72 |



### (1) 행방향으로 추가하기
<br>

✎ 6번 학생 성적이 아래와 같을 때, 성적표에 추가하기

<br>

|학생번호|국어|영어|수학|사회|과학|
|---|---|---|---|---|---|
|6|90|82|85|83|81|

<br>

In [26]:
new_score = np.array([90,82,85,83,81]) # 6번 학생의 성적

In [27]:
np.concatenate([scores,new_score],axis=0)

ValueError: all the input arrays must have same number of dimensions

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
╔══════════════════════════════╗<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
║**&nbsp;&nbsp;
⚠︎  붙이고자 하는 축방향 (0)을 제외하고, shape는 모두 같아야 합니다.** 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;║<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
╚══════════════════════════════╝


In [28]:
print("score 의 shape : ", scores.shape)         # 기존 데이터 : 6명의 5개 과목에 대한 성적표 -> shape : (6,5)
print("new score의 shape : ", new_score.shape) # 추가할 데이터 : 5개 과목에 대한 성적 나열    -> shape : (5,)

score 의 shape :  (6, 5)
new score의 shape :  (5,)


In [29]:
new_score = new_score.reshape(1,5)
new_score # 추가할 데이터에서 각 행에 있던 성적 데이터를 각 열로 이동

array([[90, 82, 85, 83, 81]])

In [30]:
print("score 의 shape : ", scores.shape)         # 기존 데이터 : 6명의 5개 과목에 대한 성적표 -> shape : (6,5)
print("new score의 shape : ", new_score.shape) # 추가할 데이터 : 1명의 5개 과목에 대한 성적  -> shape : (1,5)

score 의 shape :  (6, 5)
new score의 shape :  (1, 5)


In [31]:
np.concatenate([scores,new_score],axis=0)

array([[80, 92, 70, 65, 92],
       [91, 75, 90, 68, 85],
       [86, 76, 42, 72, 88],
       [77, 92, 52, 60, 80],
       [75, 85, 85, 92, 95],
       [96, 90, 95, 81, 72],
       [90, 82, 85, 83, 81]])

### (2) 열방향으로 추가하기

<br>

✎ 코딩 수업의 성적이 아래와 같을 때, 성적표에 추가하기

<br>

| 학생 번호 | 0 | 1 | 2 | 3 | 4 | 5 |
| ---| ---| ---| ---| ---| ---|
| 코딩 성적 | 82 | 85 |91 | 65 | 72 | 55 |

<br>

In [32]:
coding_scores = np.array([82,85,91,65,72,55])

In [33]:
print("score 의 shape : ", scores.shape)               # 기존 데이터 : 6명의 5개 과목에 대한 성적표   -> shape : (6,5)
print("coding_scores shape : ", coding_scores.shape) # 추가할 데이터 : 1개 과목에 대한 6명의 성적 나열 -> shape : (6,)

score 의 shape :  (6, 5)
coding_scores shape :  (6,)


In [34]:
coding_scores = coding_scores.reshape(6,1)

In [35]:
print("score 의 shape : ", scores.shape)               # 기존 데이터 : 6명의 5개 과목에 대한 성적표   -> shape : (6,5)
print("coding_scores shape : ", coding_scores.shape) # 추가할 데이터 : 6명의 1개 과목에 대한 성적 나열 -> shape : (6,1)

score 의 shape :  (6, 5)
coding_scores shape :  (6, 1)


In [36]:
new_scores = np.concatenate([scores, coding_scores],axis=1)
new_scores

array([[80, 92, 70, 65, 92, 82],
       [91, 75, 90, 68, 85, 85],
       [86, 76, 42, 72, 88, 91],
       [77, 92, 52, 60, 80, 65],
       [75, 85, 85, 92, 95, 72],
       [96, 90, 95, 81, 72, 55]])

<br>

## 2. np.stack()

---

+ np.concatenate() 를 통해서 같은 차원 내에서 데이터를 덧붙이는 방법을 배웠습니다.<br>
+ 이와 유사하지만, np.stack()은 특정 축 방향으로 데이터를 쌓을 때 쓰입니다.<br>
+ 즉, np.stack()은 상위 차원을 하나 만들고, 각 Array를 요소로 가지게 됩니다.

#### **데이터 1) 중간고사, 학생들의 국영수사과 성적표**

#####  

| 학생 번호 | 국어 | 영어 | 수학 | 사회 | 과학 |
|  ----   | --- |---| --- | --- | --- |
|0 |80 |92 |70 | 65 | 92 |
|1 |91 |75 |90 | 68 | 85 | 
|2 |86 |76 |42 | 72 | 88 |
|3 |77 |92 |52 | 60 | 80 |
|4 |75 |85 |85 | 92 | 95 |
|5 |96 |90 |95 | 81 | 72 |



#### 데이터 2) 기말고사, 학생들의 국영수사과 성적표


| 학생 번호 | 국어 | 영어 | 수학 | 사회 | 과학 |
|  ----   | --- |---| --- | --- | --- |
|0 |85 |95 |90 | 66 | 93 |
|1 |93 |70 |80 | 60 | 81 | 
|2 |89 |78 |55 | 75 | 80 |
|3 |80 |94 |59 | 72 | 90 |
|4 |70 |82 |81 | 95 | 72 |
|5 |90 |76 |93 | 82 | 89 |

In [37]:
final_scores = np.array([
    [85,95,90,66,93],
    [93,70,80,60,81],
    [89,78,55,75,80],
    [80,94,59,72,90],
    [70,82,81,95,72],
    [90,76,93,82,89]
])

### (1) 첫번째 축으로 중간 고사와 기말 고사 성적을 쌓기

In [38]:
print("scores의 shape : ",scores.shape)
print("final_scores의 shape : ",final_scores.shape)

scores의 shape :  (6, 5)
final_scores의 shape :  (6, 5)


In [39]:
all_scores = np.stack([scores, final_scores])

In [40]:
all_scores

array([[[80, 92, 70, 65, 92],
        [91, 75, 90, 68, 85],
        [86, 76, 42, 72, 88],
        [77, 92, 52, 60, 80],
        [75, 85, 85, 92, 95],
        [96, 90, 95, 81, 72]],

       [[85, 95, 90, 66, 93],
        [93, 70, 80, 60, 81],
        [89, 78, 55, 75, 80],
        [80, 94, 59, 72, 90],
        [70, 82, 81, 95, 72],
        [90, 76, 93, 82, 89]]])

In [41]:
all_scores[0] # 중간 고사

array([[80, 92, 70, 65, 92],
       [91, 75, 90, 68, 85],
       [86, 76, 42, 72, 88],
       [77, 92, 52, 60, 80],
       [75, 85, 85, 92, 95],
       [96, 90, 95, 81, 72]])

In [42]:
all_scores[1] # 기말 고사

array([[85, 95, 90, 66, 93],
       [93, 70, 80, 60, 81],
       [89, 78, 55, 75, 80],
       [80, 94, 59, 72, 90],
       [70, 82, 81, 95, 72],
       [90, 76, 93, 82, 89]])

In [43]:
print("all_scores의 shape : ",all_scores.shape)  # (시험 실시기준(중간|기말), 학생 번호(0~5), 과목 수(국영수사과))
# 상위 차원을 하나 만들고, 각 Array(scores, final_scores)를 요소고 갖기 때문에, (2, 6, 5)가 됩니다.

all_scores의 shape :  (2, 6, 5)


### (2) 쌓는 축 방향을 다르게 설정하기
쌓는 축의 방향은 다양하게 설정하여 원하는 형태의 Numpy Array로 쌓을 수 있습니다.

In [44]:
all_scores = np.stack([scores, final_scores],axis=2)

In [45]:
all_scores # 중간고사 성적, 기말고사 성적을 교차해서 보고 싶다면, 이런 방식도 있음

array([[[80, 85],
        [92, 95],
        [70, 90],
        [65, 66],
        [92, 93]],

       [[91, 93],
        [75, 70],
        [90, 80],
        [68, 60],
        [85, 81]],

       [[86, 89],
        [76, 78],
        [42, 55],
        [72, 75],
        [88, 80]],

       [[77, 80],
        [92, 94],
        [52, 59],
        [60, 72],
        [80, 90]],

       [[75, 70],
        [85, 82],
        [85, 81],
        [92, 95],
        [95, 72]],

       [[96, 90],
        [90, 76],
        [95, 93],
        [81, 82],
        [72, 89]]])

In [46]:
all_scores[:,:,0] # 중간 고사 성적

array([[80, 92, 70, 65, 92],
       [91, 75, 90, 68, 85],
       [86, 76, 42, 72, 88],
       [77, 92, 52, 60, 80],
       [75, 85, 85, 92, 95],
       [96, 90, 95, 81, 72]])

In [47]:
all_scores[:,:,1] # 기말 고사 성적

array([[85, 95, 90, 66, 93],
       [93, 70, 80, 60, 81],
       [89, 78, 55, 75, 80],
       [80, 94, 59, 72, 90],
       [70, 82, 81, 95, 72],
       [90, 76, 93, 82, 89]])

#  

---

    Copyright(c) 2019 by Public AI. All rights reserved.
    Writen by PAI, SangJae Kang ( rocketgrowthsj@publicai.co.kr )  last updated on 2019/03/04


---