 ╔══<i><b>Alai-DeepLearning</b></i>═══════════════════════════════╗
###  &nbsp;&nbsp; **✎&nbsp;&nbsp;Week 2. Numpy Basis**
# Section 4. Numpy의 주요 함수들(1)


### _Objective_
1. Numpy Array의 각각 원소에 대해 특정 연산을 실행해 주어야 할 때가 있습니다.<br>
1. Numpy Array에서 원소 단위로 연산을 적용하는 범용함수(ufunc ; universal function)에 대해 배워봅시다.<br>
  
╚════════════════════════════════════════════╝


In [0]:
import numpy as np

# \[ 1. Numpy array의 universal Function \]

----

----

> *`np.array`는 Python 기본 함수와 마찬가지로 기본적인 사칙 연산을 제공합니다.*<br>
> _우리는 감가승제( -, +, \*, / )를 Python 기본 함수와 비슷한 방법으로 사용할수 있습니다._

## 1. Array & Scalar 사칙연산

---

* Array와 하나의 값을 연산할 때에는 Array의 **모든 원소**에 적용됩니다.

### (1) Array에 Scalar 값 더하기 ( + )

In [0]:
A = np.arange(0,3) # 0 ~ 2 까지의 Numpy Array를 생성
A

array([0, 1, 2])

In [0]:
A + 5

array([5, 6, 7])

전역적으로 Numpy Array 의 모든 원소에 1씩 더해진 결과를 확인할 수 있습니다.

일부분만 더하고 싶다면, Indexing으로 지정하여 범위를 지정할 수도 있습니다.

In [0]:
A = np.arange(0,3,dtype=np.float)
A[:2] = A[:2] + 5 # 0~1까지의 index에만 5를 더함
A

array([5., 6., 2.])

In [0]:
A = np.arange(0,3,dtype=np.float)
A[[0,2]] = A[[0,2]] + 5 # 0과 2의 index에만 5를 더함
A

array([5., 1., 7.])

### (2) Array에 Scalar 값 빼기 ( - )

In [0]:
A = np.arange(0,3)
A

array([0, 1, 2])

In [0]:
A - 2

array([-2, -1,  0])

### (3) Array에 Scalar 값 곱하기 ( \* )

In [0]:
A = np.arange(0,3)
A

array([0, 1, 2])

In [0]:
A * 3

array([0, 3, 6])

### (4) Array에 Scalar 값 나누기 ( / )

In [0]:
A = np.arange(0,3)
A

array([0, 1, 2])

In [0]:
A / 3

array([0, 1, 0])

## 2. 같은 크기의 Array 간 사칙연산

---

* **같은** 크기의 Array 간 사칙연산을 할 때에는 **같은 위치의 Element끼리 연산**한 결과를 반환합니다.

### (1) Array와 Array 간 더하기 ( + )

In [0]:
A = np.arange(0,3)
B = np.arange(5,8)
A, B

(array([0, 1, 2]), array([5, 6, 7]))

In [0]:
A + B

array([5, 7, 9])

### (2) Array와 Array간 빼기 ( - )

In [0]:
A = np.arange(0,3)
B = np.arange(5,8)
A, B

In [0]:
A - B

array([-5, -5, -5])

### (3) Array와 Array간 곱하기( * )

In [0]:
A = np.arange(0,3)
B = np.arange(5,8)
A, B

In [0]:
A * B

array([ 0,  6, 14])

### (4) Array와 Array간 나누기 ( / )

In [0]:
A = np.arange(0,3)
B = np.arange(5,8)
A, B

(array([0, 1, 2]), array([5, 6, 7]))

In [0]:
A / B

array([0.        , 0.16666667, 0.28571429])

## 3. 다른 크기의 Array 간 사칙연산

---

+ 서로 다른 크기를 갖는 Array 간 사칙연산을 적용할 때는 어떻게 연산되는지 확인해 봅시다.

### (1) 다른 크기의 Array 간 사칙연산

* **다른** 크기의 Array 간 연산할 때에는 **Broadcasting의 법칙에 따라 연산**이 적용됩니다.
* Broadcasting : 연산이 가능해지도록 배열을 자동적으로 변환

![](http://www.astroml.org/_images/fig_broadcast_visual_1.png)

In [0]:
A = np.ones((3,3))
B = np.arange(3)
print("A : \n", A)
print("B : \n", B)

A : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
B : 
 [0 1 2]


In [0]:
A + B

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [0]:
np.arange(3).reshape((3,1)) + np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### # Broadcasting  ───────────────────

+ 모양이 서로 다른 Numpy Array를 연산이 가능하도록 자동으로 바꾸어주는 Broadcasting은 매우 편한 기능입니다. 
+ 아래의 예시를 통해 살펴봅시다.
+ [Broadcasting 참고자료](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html)

#### 데이터) 중간고사, 학생들의 국영수사과 성적표

| 학생 번호 | 국어 | 영어 | 수학 | 사회 | 과학 |
|  ----   | --- |---| --- | --- | --- |
|0 |80 |92 |70 | 65 | 92 |
|1 |91 |75 |90 | 68 | 85 | 
|2 |86 |76 |42 | 72 | 88 |
|3 |77 |92 |52 | 60 | 80 |
|4 |75 |85 |85 | 92 | 95 |
|5 |96 |90 |95 | 81 | 72 |

In [0]:
scores = np.array([
    [80,92,70,65,92],
    [91,75,90,68,85],
    [86,76,42,72,88],
    [77,92,52,60,80],
    [75,85,85,92,95],
    [96,90,95,81,72]
])
scores

array([[80, 92, 70, 65, 92],
       [91, 75, 90, 68, 85],
       [86, 76, 42, 72, 88],
       [77, 92, 52, 60, 80],
       [75, 85, 85, 92, 95],
       [96, 90, 95, 81, 72]])

#### 예시)

번호가 1번인 학생이 자신의 성적 대비 친구들과의 과목 별 성적 차이가 어떻게 나는지 계산하고자 합니다.

#### ⓵ broad casting 없이 코드를 짰을 때

In [0]:
my_score = scores[1] # 학생 1번의 성적

diff_scores = scores.copy()
for row_idx in range(scores.shape[0]):
    # For구문을 통해 직접 순회하며 하나씩 연산을 적용해야 합니다.
    diff_scores[row_idx] -= my_score
    
diff_scores

array([[-11,  17, -20,  -3,   7],
       [  0,   0,   0,   0,   0],
       [ -5,   1, -48,   4,   3],
       [-14,  17, -38,  -8,  -5],
       [-16,  10,  -5,  24,  10],
       [  5,  15,   5,  13, -13]])

#### ⓶ Broad Casting을 이용하여 코드를 돌린다면

In [0]:
my_score = scores[1] # 학생 1번의 성적

scores - my_score # 자동으로 아래까지 전부 연산이 돌아갑니다.

array([[-11,  17, -20,  -3,   7],
       [  0,   0,   0,   0,   0],
       [ -5,   1, -48,   4,   3],
       [-14,  17, -38,  -8,  -5],
       [-16,  10,  -5,  24,  10],
       [  5,  15,   5,  13, -13]])

#### **Numpy의 BroadCasting 덕분에 불필요한 For 구문을 피하며, 직관적으로 코드를 구현할 수 있게 됩니다.**<br><br>

───────────────────────────────


## 4. 이 외에도 다양한 연산함수들

---

* numpy 패키지는 수학, 공학에서 필요한 매우 많은 주요 연산들을 구현되어 있습니다.

In [0]:
A = np.arange(1,5,0.5)
A

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

### (1) sin 함수

$y = sin(x)$을 원소 별로 적용하여 결과를 반환합니다.

In [0]:
np.sin(A)

array([ 0.84147098,  0.99749499,  0.90929743,  0.59847214,  0.14112001,
       -0.35078323, -0.7568025 , -0.97753012])

### (2) 지수 함수

$y=e^x$을 원소 별로 적용하여 결과를 반환합니다.

In [0]:
np.exp(A)

array([ 2.71828183,  4.48168907,  7.3890561 , 12.18249396, 20.08553692,
       33.11545196, 54.59815003, 90.0171313 ])

### (3) 로그 함수

$y = log(x)$을 원소 별로 적용하여 결과를 반환합니다.

In [0]:
np.log(A)

array([0.        , 0.40546511, 0.69314718, 0.91629073, 1.09861229,
       1.25276297, 1.38629436, 1.5040774 ])

### (4) 행렬 곱 함수

딥러닝에서 가장 중요한 연산 중 하나인, 행렬곱 연산도 아래처럼 간단히 구현할 수 있습니다.

In [0]:
W = np.array([
    [1,2,3],
    [2,3,4],
    [3,4,5]
])

X = np.array([
    [1],
    [2],
    [3],
])

In [0]:
np.matmul(W,X)

array([[14],
       [20],
       [26]])

#  

---

    Copyright(c) 2019 by Public AI. All rights reserved.<br>
    Writen by PAI, SangJae Kang ( rocketgrowthsj@publicai.co.kr )  last updated on 2019/03/04

---