 ╔══<i><b>Alai-DeepLearning</b></i>═══════════════════════════╗
###  &nbsp;&nbsp; **✎&nbsp;&nbsp;Day 2. Numpy Basis**
# Section 4. Numpy의 주요 함수들(2)

### _Objective_
1. Numpy Array의 하나의 축으로 각 원소들의 통계적 수치가 필요할 때가 있습니다.<br>
2. Numpy Array에서 축을 따라 연산하는 집계함수들(sum, mean 등)대해 배워봅시다.<br>

╚════════════════════════════════════════╝

In [0]:
import numpy as np

# \[ 1. Numpy array의 축 연산 \]

---

---

> _`np.array`는 축을 기준으로 집계 계산하는, sum, mean, std, max, min 등의 연산을 지원합니다._<br>
> _집계함수는 한 축이 갖는 여러개의 값을  그룹당 하나의 값으로 반환합니다._

## 예제 데이터 )  학생들의 국영수사과 성적표



#### 데이터 1) 중간고사, 학생들의 국영수사과 성적표
`middle_scores`

| 학생 번호 | 국어 | 영어 | 수학 | 사회 | 과학 |
|  ----   | --- |---| --- | --- | --- |
|0 |80 |92 |70 | 65 | 92 |
|1 |91 |75 |90 | 68 | 85 | 
|2 |86 |76 |42 | 72 | 88 |
|3 |77 |92 |52 | 60 | 80 |
|4 |75 |85 |85 | 92 | 95 |
|5 |96 |90 |95 | 81 | 72 |

#### 데이터 2) 기말고사, 학생들의 국영수사과 성적표
`final_scores`

| 학생 번호 | 국어 | 영어 | 수학 | 사회 | 과학 |
|  ----   | --- |---| --- | --- | --- |
|0 |85 |95 |90 | 66 | 93 |
|1 |93 |70 |80 | 60 | 81 | 
|2 |89 |78 |55 | 75 | 80 |
|3 |80 |94 |59 | 72 | 90 |
|4 |70 |82 |81 | 95 | 72 |
|5 |90 |76 |93 | 82 | 89 |

In [0]:
middle_scores = np.array([
    [80,92,70,65,92],
    [91,75,90,68,85],
    [86,76,42,72,88],
    [77,92,52,60,80],
    [75,85,85,92,95],
    [96,90,95,81,72]
])

final_scores = np.array([
    [85,95,90,66,93],
    [93,70,80,60,81],
    [89,78,55,75,80],
    [80,94,59,72,90],
    [70,82,81,95,72],
    [90,76,93,82,89]
])

scores = np.stack([middle_scores,final_scores])

scores

[[[80 92 70 65 92]
  [91 75 90 68 85]
  [86 76 42 72 88]
  [77 92 52 60 80]
  [75 85 85 92 95]
  [96 90 95 81 72]]

 [[85 95 90 66 93]
  [93 70 80 60 81]
  [89 78 55 75 80]
  [80 94 59 72 90]
  [70 82 81 95 72]
  [90 76 93 82 89]]]


In [0]:
scores.shape

(2, 6, 5)

## 1. Numpy Array에서 축을 중심으로 평균 구하기

---

+ Numpy에서는 간단히 축을 설정하는 것 만으로도 다양한 기준에 따른 연산 값을 구할 수 있습니다.<br>
+ axis의 value는 numpy Array의 shape에서 몇번째 축인지 결정해주는 parameter입니다.

In [0]:
scores.shape

(2, 6, 5)

axis = 0 에서 2 : 각 기간(중간고사, 기말고사)를 의미<br>
axis = 1 에서 6 : 여섯명의 학생들을 의미<br>
axis = 2 에서 5 : 다섯개의 과목들을 의미<br>

### 예제 1) 전체 평균 점수 

중간, 기말을 통틀어, 학생들이 받는 평균 성적은 얼마인가? 

In [0]:
scores.mean()

80.23333333333333

### 예제 2) 학생 & 과목 별 평균 점수 

학생들의 최종 성적을 구하기 위해, 학생들의 과목 별 평균 성적( 중간과 기말의 평균 )을 구해보자.<br>
(각 학생들의 각 과목별 중간, 기말의 평균)

In [0]:
scores.shape
# axis = 0 : 2 ( 중간고사, 기말고사 )의 값을 하나로
# 기간의 구분 없이 각 학생, 과목별 평균 -> axis = 0에 대해 평균

(2, 6, 5)

In [0]:
scores.mean(axis=0)

array([[82.5, 93.5, 80. , 65.5, 92.5],
       [92. , 72.5, 85. , 64. , 83. ],
       [87.5, 77. , 48.5, 73.5, 84. ],
       [78.5, 93. , 55.5, 66. , 85. ],
       [72.5, 83.5, 83. , 93.5, 83.5],
       [93. , 83. , 94. , 81.5, 80.5]])

In [0]:
scores.mean(axis=0).shape
# axis : 0 의 값 (2 => 1)

(6, 5)

### 예제 3) 기간 & 과목 별 평균 점수 

과목 별로 중간 기말의 성적 차이가 어떤 식으로 나는지 확인하기 위해, 과목 별 중간 기말 평균 점수을 구해보자. <br>
(각 기간별로 각 과목별 모든 학생들의 평균)

In [0]:
scores.shape
# axis = 1 : 6 ( 각 학생들 )의 값을 하나로
# 학생들의 구분 없이 각 기간, 각 과목별 평균 -> axis = 1에 대해 평균

(2, 6, 5)

In [0]:
scores.mean(axis=1)

array([[84.16666667, 85.        , 72.33333333, 73.        , 85.33333333],
       [84.5       , 82.5       , 76.33333333, 75.        , 84.16666667]])

In [0]:
scores.mean(axis=1).shape
# axis : 1의 값 (6 => 1)

(2, 5)

### 예제 4) 학생 & 기간 별 평균 점수

학생 별로 중간 고사 대비 기말 고사가 얼마나 올라갔는지 확인하기 위해, 학생 별 중간 기말 평균 점수를 구해보자. <br>
(각 학생, 기간별 모든 과목의 평균)

In [0]:
scores.shape
# axis = 2 : 5 ( 각 과목 )의 값을 하나로
# 과목에 구분없이, 각 학생별, 각 기간별 평균 -> axis=2 에 대해 평균

(2, 6, 5)

In [0]:
scores.mean(axis=2)

array([[79.8, 81.8, 72.8, 72.2, 86.4, 86.8],
       [85.8, 76.8, 75.4, 79. , 80. , 86. ]])

In [0]:
scores.mean(axis=2).shape
# axis : 2 의 값 (5 => 1)

(2, 6)

### 예제 5) 학생 별 평균 점수 

학생의 1학기 학업 등수를 내기 위해, 학생 별 전체 평균 성적을 구해 보자. <br>
(각 학생들의 모든 과목, 기간의 평균)

In [0]:
scores.shape
# axis = 0 : 2 ( 각 기간 ), axis = 2 : 5 ( 각 과목 )의 값을 하나로 
# shape ( 2, 6, 5 ) -> (6, ) 
# 각 학생별로 받은 모든 성적의 평균을 구하고자함

(2, 6, 5)

In [0]:
average_per_period = scores.mean(axis=0) # 기간 축으로 평균
average_per_period # 학생/과목 별 평균 성적

array([[82.5, 93.5, 80. , 65.5, 92.5],
       [92. , 72.5, 85. , 64. , 83. ],
       [87.5, 77. , 48.5, 73.5, 84. ],
       [78.5, 93. , 55.5, 66. , 85. ],
       [72.5, 83.5, 83. , 93.5, 83.5],
       [93. , 83. , 94. , 81.5, 80.5]])

In [0]:
average_per_period.shape
# 기간의 구분 없이 평균값이 적용됨
# 두개의 기간 각각의 값 -> 하나의 평균값 : shape ( 2, 6, 5 ) -> (6, 5) 

(6, 5)

In [0]:
average_per_period.mean(axis=1) # 과목 축으로 평균
# 학생의 평균 성적

array([82.8, 79.3, 74.1, 75.6, 83.2, 86.4])

In [0]:
average_per_period.mean(axis=1).shape
# 과목의 구분 없이 평균값이 적용됨
# 다섯개의 과목 각각의 값 -> 하나의 평균값 : shape ( 6, 5 ) -> (6, ) 

(6,)

**이렇게 Chaining 방식으로 평균을 구할 수도 있습니다.**

In [0]:
scores.shape

(2, 6, 5)

In [0]:
scores.mean(axis=0).mean(axis=1)

array([82.8, 79.3, 74.1, 75.6, 83.2, 86.4])

In [0]:
scores.mean(axis=0).mean(axis=1).shape
# 각 학생들의 모든 점수 평균값

(6,)

### 예제 6) 과목 별 평균 점수 

1학기 과목별 난이도를 평가하기 위해, 과목별 전체 평균 성적을 구해 보자.<br>
(각 과목들의 모든 학생, 기간의 평균)

In [0]:
scores.shape
# axis = 0 : 2 ( 각 기간 ), axis = 1 : 6 ( 각 학생 )의 값을 하나로 
# shape ( 2, 6, 5 ) -> (5, ) 
# 각 과목별로 받은 모든 성적의 평균을 구하고자함

(2, 6, 5)

In [0]:
average_per_period = scores.mean(axis=0) # 기간 축으로 평균
average_per_period # 학생/과목 별 평균 성적

array([[82.5, 93.5, 80. , 65.5, 92.5],
       [92. , 72.5, 85. , 64. , 83. ],
       [87.5, 77. , 48.5, 73.5, 84. ],
       [78.5, 93. , 55.5, 66. , 85. ],
       [72.5, 83.5, 83. , 93.5, 83.5],
       [93. , 83. , 94. , 81.5, 80.5]])

In [0]:
average_per_period.shape
# 기간의 구분 없이 평균값이 적용됨
# 두개의 기간 각각의 값 -> 하나의 평균값 : shape ( 2, 6, 5 ) -> (6, 5)

(6, 5)

In [0]:
average_per_period.mean(axis=0) # 학생 축으로 평균
# 과목의 평균 성적

array([84.33333333, 83.75      , 74.33333333, 74.        , 84.75      ])

In [0]:
average_per_period.mean(axis=0).shape
# 학생의 구분 없이 평균값이 적용됨
# 여섯명의 학생 각각의 값 -> 하나의 평균값 : shape ( 6, 5 ) -> (5, ) 

(5,)

**이렇게 Chaining 방식으로 평균을 구할 수도 있습니다.**

In [0]:
scores.shape

(2, 6, 5)

In [0]:
scores.mean(axis=0).mean(axis=0)

array([84.33333333, 83.75      , 74.33333333, 74.        , 84.75      ])

In [0]:
scores.mean(axis=0).mean(axis=0).shape
# 각 과목들의 모든 점수 평균값

(5,)

┌─<i> ✍︎ Example  &nbsp;&nbsp;&nbsp;</i>─────────────────────────┐ <br>

│ Numpy의 집계함수를 이용하여  "기간 별 평균 점수"를 계산해 보세요. &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;│<br>
  
   
└─────────────────────────────────┘

In [0]:
# 실습공간



## 2. Numpy Array에서 다른 집계함수들의 적용

---


+ 평균 이외에도 `min`, `max`, `std`, `sum` 등의 함수가 동작합니다.
+ 아래의 예시를 통해 다양하게 적용해 봅시다.

### 예제 1) 전체를 기준으로 적용

In [0]:
np.sum(scores) # 전체 합

4814

In [0]:
np.max(scores) # 전체 중 최대값

96

In [0]:
np.min(scores) # 전체 중 최소값

42

In [0]:
np.std(scores) # 전체의 표준 편자

12.083551722164401

### 예제 2) 학생 & 과목 별로 적용

In [0]:
np.sum(scores,axis=0) # 학생 & 과목 별 합

array([[165, 187, 160, 131, 185],
       [184, 145, 170, 128, 166],
       [175, 154,  97, 147, 168],
       [157, 186, 111, 132, 170],
       [145, 167, 166, 187, 167],
       [186, 166, 188, 163, 161]])

In [0]:
np.max(scores,axis=0) # 학생 & 과목 별 최대값

array([[85, 95, 90, 66, 93],
       [93, 75, 90, 68, 85],
       [89, 78, 55, 75, 88],
       [80, 94, 59, 72, 90],
       [75, 85, 85, 95, 95],
       [96, 90, 95, 82, 89]])

In [0]:
np.min(scores,axis=0) # 학생 & 과목 별 최소값

array([[80, 92, 70, 65, 92],
       [91, 70, 80, 60, 81],
       [86, 76, 42, 72, 80],
       [77, 92, 52, 60, 80],
       [70, 82, 81, 92, 72],
       [90, 76, 93, 81, 72]])

In [0]:
np.std(scores,axis=0) # 학생 & 과목 별 표준 편자

array([[ 2.5,  1.5, 10. ,  0.5,  0.5],
       [ 1. ,  2.5,  5. ,  4. ,  2. ],
       [ 1.5,  1. ,  6.5,  1.5,  4. ],
       [ 1.5,  1. ,  3.5,  6. ,  5. ],
       [ 2.5,  1.5,  2. ,  1.5, 11.5],
       [ 3. ,  7. ,  1. ,  0.5,  8.5]])

### 예제 3) 기간 & 과목 별로 적용


In [0]:
np.sum(scores,axis=1) # 기간 & 과목 별 합

array([[505, 510, 434, 438, 512],
       [507, 495, 458, 450, 505]])

In [0]:
np.max(scores,axis=1) # 기간 & 과목 별 최대값

array([[96, 92, 95, 92, 95],
       [93, 95, 93, 95, 93]])

In [0]:
np.min(scores,axis=1) # 기간 & 과목 별 최소값

array([[75, 75, 42, 60, 72],
       [70, 70, 55, 60, 72]])

In [0]:
np.std(scores,axis=1) # 기간 & 과목 별 표준 편자

array([[ 7.55902698,  7.11805217, 19.68643075, 10.67707825,  7.65216019],
       [ 7.67571929,  9.19691977, 14.46451597, 11.28420725,  7.19760763]])

### 예제 4) 학생 & 기간 별 적용


In [0]:
np.sum(scores,axis=2) # 기간 & 과목 별 합

array([[399, 409, 364, 361, 432, 434],
       [429, 384, 377, 395, 400, 430]])

In [0]:
np.max(scores,axis=2) # 기간 & 과목 별 최대값

array([[92, 91, 88, 92, 95, 96],
       [95, 93, 89, 94, 95, 93]])

In [0]:
np.min(scores,axis=2) # 기간 & 과목 별 최소값

array([[65, 68, 42, 52, 75, 72],
       [66, 60, 55, 59, 70, 76]])

In [0]:
np.std(scores,axis=2) # 기간 & 과목 별 표준 편자

array([[11.070682  ,  8.93084542, 16.52150114, 14.37219538,  6.91664659,
         9.10823803],
       [10.45753317, 11.12474719, 11.21784293, 12.61744824,  8.87693641,
         6.164414  ]])

#  

---

    Copyright(c) 2019 by Public AI. All rights reserved.<br>
    Writen by PAI, SangJae Kang ( rocketgrowthsj@publicai.co.kr )  last updated on 2019/03/04

---