 ╔══<i><b>Alai-DeepLearning</b></i>═══════════════════════════╗
###  &nbsp;&nbsp; **✎&nbsp;&nbsp;week 4. Tensorflow basis **
# Section 3. Tensor을 다루는 함수들

### _Objective_
1. 인덱싱에 관련된 메소드에 대해 배워봅니다. <br>
2. 차원에 관련된 메소드에 대해 배워봅니다. <br>
3. 텐서를 합치고 쪼개는 메소드에 대해 배워봅니다. <br>
4. 텐서를 생성하는 메소드에 대해 배워봅니다. 

╚════════════════════════════════════════╝

In [1]:
%matplotlib inline
import numpy as np
import tensorflow as tf 
import matplotlib.pyplot as plt

### [Optional.  eager_execution 이용하기 ]

---

> _`tensorflow` 2.0 버전부터 지원하게 된 기능으로, graph와 session을 따로 만들어서 실행하지 않고, **즉시 실행**가능하도록 만든 기능입니다._<br>
> _이번 실습시간에서는 eager execution으로 실습을 진행하겠습니다. <br>

In [2]:
# Tensorflow
tf.enable_eager_execution()

In [3]:
# eager execution은 아래와 같이 나옵니다.
a = tf.constant(1)
b = tf.constant(2)
tf.add(a,b)

<tf.Tensor: id=2, shape=(), dtype=int32, numpy=3>

In [4]:
# 이런식으로 우리는 바로 출력 값을 확인할 수 있습니다.
tf.add(a,b).numpy()

3

# \[ 1. Tensor 조작하기  \]

---
---


> Tensor는 수학적으로 고차원의 행렬을 의미합니다. Tensorflow에서는 Tensor을 조작하기 위해 다양한 메소드들을 제공합니다. 이번 시간에서는 텐서를 어떻게 조작하는지에 대해 배워보겠습니다.

## 예제 데이터 )  학생들의 국영수사과 성적표


#### 데이터 1) 중간고사, 학생들의 국영수사과 성적표
`middle_scores`

| 학생 번호 | 국어 | 영어 | 수학 | 사회 | 과학 |
|  ----   | --- |---| --- | --- | --- |
|0 |80 |92 |70 | 65 | 92 |
|1 |91 |75 |90 | 68 | 85 | 
|2 |86 |76 |42 | 72 | 88 |
|3 |77 |92 |52 | 60 | 80 |
|4 |75 |85 |85 | 92 | 95 |
|5 |96 |90 |95 | 81 | 72 |

#### 데이터 2) 기말고사, 학생들의 국영수사과 성적표
`final_scores`

| 학생 번호 | 국어 | 영어 | 수학 | 사회 | 과학 |
|  ----   | --- |---| --- | --- | --- |
|0 |85 |95 |90 | 66 | 93 |
|1 |93 |70 |80 | 60 | 81 | 
|2 |89 |78 |55 | 75 | 80 |
|3 |80 |94 |59 | 72 | 90 |
|4 |70 |82 |81 | 95 | 72 |
|5 |90 |76 |93 | 82 | 89 |

In [5]:
middle_scores = np.array([
    [80,92,70,65,92],
    [91,75,90,68,85],
    [86,76,42,72,88],
    [77,92,52,60,80],
    [75,85,85,92,95],
    [96,90,95,81,72]
])

final_scores = np.array([
    [85,95,90,66,93],
    [93,70,80,60,81],
    [89,78,55,75,80],
    [80,94,59,72,90],
    [70,82,81,95,72],
    [90,76,93,82,89]
])

# Numpy array
scores = np.stack([middle_scores,final_scores])

# Tensor로 만들기
scores_tensor = tf.constant(scores)

scores_tensor.numpy()

array([[[80, 92, 70, 65, 92],
        [91, 75, 90, 68, 85],
        [86, 76, 42, 72, 88],
        [77, 92, 52, 60, 80],
        [75, 85, 85, 92, 95],
        [96, 90, 95, 81, 72]],

       [[85, 95, 90, 66, 93],
        [93, 70, 80, 60, 81],
        [89, 78, 55, 75, 80],
        [80, 94, 59, 72, 90],
        [70, 82, 81, 95, 72],
        [90, 76, 93, 82, 89]]])

 ## 1. 인덱싱에 관련된 메소드

---

+ Tensor에서 원하는 원소 혹은 배열의 값을 가져오는 여러가지 메소드에 대해 배워보겠습니다.

### (1) tf.boolean_mask  
numpy에서의 boolean mask는 `arr[<boolean mask>]`와 같은 방식으로 이루어집니다.<br> 
하지만 텐서플로우에서는 numpy와는 조금 다른 형태로 지원합니다. 


#### 1) numpy로 boolean mask를 할 경우

In [6]:
# 성적이 80점보다 높은지에 대한 True/False
scores>80

array([[[False,  True, False, False,  True],
        [ True, False,  True, False,  True],
        [ True, False, False, False,  True],
        [False,  True, False, False, False],
        [False,  True,  True,  True,  True],
        [ True,  True,  True,  True, False]],

       [[ True,  True,  True, False,  True],
        [ True, False, False, False,  True],
        [ True, False, False, False, False],
        [False,  True, False, False,  True],
        [False,  True,  True,  True, False],
        [ True, False,  True,  True,  True]]])

In [7]:
# 80점이상의 성적만 가져오기
scores[scores>80]

array([92, 92, 91, 90, 85, 86, 88, 92, 85, 85, 92, 95, 96, 90, 95, 81, 85,
       95, 90, 93, 93, 81, 89, 94, 90, 82, 81, 95, 90, 93, 82, 89])

#### 2) tensorflow로 boolean mask를 할 경우

In [8]:
# Numpy와 같이 적용하면 에러가 발생합니다. 
scores_tensor[scores_tensor>80]

TypeError: Only integers, slices (`:`), ellipsis (`...`), tf.newaxis (`None`) and scalar tf.int32/tf.int64 tensors are valid indices, got <tf.Tensor: id=9, shape=(2, 6, 5), dtype=bool, numpy=
array([[[False,  True, False, False,  True],
        [ True, False,  True, False,  True],
        [ True, False, False, False,  True],
        [False,  True, False, False, False],
        [False,  True,  True,  True,  True],
        [ True,  True,  True,  True, False]],

       [[ True,  True,  True, False,  True],
        [ True, False, False, False,  True],
        [ True, False, False, False, False],
        [False,  True, False, False,  True],
        [False,  True,  True,  True, False],
        [ True, False,  True,  True,  True]]])>

In [ ]:
# tf.boolean_mask를 이용하면 가능합니다.
tf.boolean_mask(scores_tensor,
                scores_tensor>80).numpy()

### (2) tf.gather_nd
tf.gather_nd는 `scores_tensor[0]`같이 기본적인 Indexing 기능을 좀 더 일반화한 기능입니다.

#### 1)  중간고사 성적 가져오기

In [ ]:
# 기본 Indexing
scores_tensor[0].numpy()

In [ ]:
# gather_nd를 통한 인덱싱
# [0] -> [0,:,:]과 동일합니다.
tf.gather_nd(scores_tensor,[0]).numpy()

#### 2) 1번 학생의 중간고사 성적과 2번 학생의 기말고사 성적 가져오기

tf.gather_nd는 원하는 indexing의 원소들을 한번에 가져올 수 있습니다.

In [ ]:
# 1번 학생의 중간고사 성적
# [0,1] -> [0,1,:]과 동일합니다.
tf.gather_nd(scores_tensor,[0,1]).numpy()

In [ ]:
# 2번 학생의 기말고사 성적
# [1,2] -> [1,2,:]과 동일합니다.
tf.gather_nd(scores_tensor,[1,2]).numpy()

In [ ]:
# 같이 가져오기
tf.gather_nd(scores_tensor,[[0,1],[1,2]]).numpy()

>numpy의 [1,:,2] 처럼 가져올 수는 없습니다.<br> 
이렇게 가져오고자 하면, 이후 `tf.transpose`와 함께 사용해야 합니다.

#### 3) 1번 학생의 중간고사 수학성적 가져오기

In [ ]:
# [0,1,2]
tf.gather_nd(scores_tensor,[0,1,2]).numpy()

### (3) tf.where
tf.where는 numpy.where과 동일하게 동작합니다.<br>
1. 조건문만 있는 경우 -> 조건에 만족하는 원소들의 인덱스 위치값을 반환합니다.
2. `x`,`y`가 있는 경우 -> 조건에 만족하는 위치에 값을 참인 경우, `x`로, 거짓인 경우 `y`로 바꾸어 줍니다.


#### 1) 조건문만 있는 경우

* 95점보다 높거나 같은 성적들을 가져오겠습니다.

In [9]:
# 95점보다 높은 값들인지 확인
(scores_tensor>=95).numpy()

array([[[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False,  True],
        [ True, False,  True, False, False]],

       [[False,  True, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False,  True, False],
        [False, False, False, False, False]]])

In [10]:
# Boolean의 값이 참인 원소의 위치를 가져옴
indices_list = tf.where(scores_tensor>=95).numpy()
indices_list

array([[0, 4, 4],
       [0, 5, 0],
       [0, 5, 2],
       [1, 0, 1],
       [1, 4, 3]])

In [11]:
# gather_nd를 통해 95점 이상의 값들을 가져올 수 있습니다.
tf.gather_nd(scores_tensor, indices_list).numpy()

array([95, 96, 95, 95, 95])

#### 2) `x`,`y`가 있는 경우

* 중간 고사 성적과 기말 고사 성적을 비교해서 학생이 받은 각 과목 별 최고 성적을 구해보겠습니다.

In [12]:
middle_tensor = scores_tensor[0] 
final_tensor = scores_tensor[1]

In [13]:
tf.where(middle_tensor>final_tensor, 
         middle_tensor, # 참인 경우 중간고사 성적이 들어감
         final_tensor   # 거짓인 경우 기말고사 성적이 들어감
        ) 

<tf.Tensor: id=30, shape=(6, 5), dtype=int64, numpy=
array([[85, 95, 90, 66, 93],
       [93, 75, 90, 68, 85],
       [89, 78, 55, 75, 88],
       [80, 94, 59, 72, 90],
       [75, 85, 85, 95, 95],
       [96, 90, 95, 82, 89]])>

## 2. 차원을 다루는 메소드들 

---

+ Tensor의 형태, 차원은 원소의 갯수가 동일하다는 가정 하에 쉽게 바꿀 수 있습니다.

### (1) tf.shape
Tensor의 shape는 위의 메소드로 쉽게 확인할 수 있습니다.

In [14]:
# Shape의 결과도 Tensor로 나옵니다.
tf.shape(scores_tensor)

<tf.Tensor: id=32, shape=(3,), dtype=int32, numpy=array([2, 6, 5], dtype=int32)>

> scores_tensor의 크기에 따라 같은 크기의 1로 만들어진 Tensor을 만드는 등,
  Tensor의 크기에 따라 동적으로 바뀌어야 할 때 주로 쓰입니다.

In [15]:
# scores_tensor와 같은 크기의 행렬 만들기
tf.ones(tf.shape(scores_tensor))

<tf.Tensor: id=36, shape=(2, 6, 5), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)>

### (2) tf.reshape
Tensor의 shape을 바꾸어 줍니다. **원소의 순서를 바꾸지 않습니다.**

In [16]:
tf.reshape(scores_tensor,[12,5]) # (2,6,5) -> (12,5)

<tf.Tensor: id=39, shape=(12, 5), dtype=int64, numpy=
array([[80, 92, 70, 65, 92],
       [91, 75, 90, 68, 85],
       [86, 76, 42, 72, 88],
       [77, 92, 52, 60, 80],
       [75, 85, 85, 92, 95],
       [96, 90, 95, 81, 72],
       [85, 95, 90, 66, 93],
       [93, 70, 80, 60, 81],
       [89, 78, 55, 75, 80],
       [80, 94, 59, 72, 90],
       [70, 82, 81, 95, 72],
       [90, 76, 93, 82, 89]])>

In [17]:
tf.reshape(scores_tensor,[-1,5]) # (2,6,5) -> (12,5)

<tf.Tensor: id=42, shape=(12, 5), dtype=int64, numpy=
array([[80, 92, 70, 65, 92],
       [91, 75, 90, 68, 85],
       [86, 76, 42, 72, 88],
       [77, 92, 52, 60, 80],
       [75, 85, 85, 92, 95],
       [96, 90, 95, 81, 72],
       [85, 95, 90, 66, 93],
       [93, 70, 80, 60, 81],
       [89, 78, 55, 75, 80],
       [80, 94, 59, 72, 90],
       [70, 82, 81, 95, 72],
       [90, 76, 93, 82, 89]])>

In [18]:
tf.reshape(scores_tensor,[-1]) # 1자로 펴줍니다.

<tf.Tensor: id=45, shape=(60,), dtype=int64, numpy=
array([80, 92, 70, 65, 92, 91, 75, 90, 68, 85, 86, 76, 42, 72, 88, 77, 92,
       52, 60, 80, 75, 85, 85, 92, 95, 96, 90, 95, 81, 72, 85, 95, 90, 66,
       93, 93, 70, 80, 60, 81, 89, 78, 55, 75, 80, 80, 94, 59, 72, 90, 70,
       82, 81, 95, 72, 90, 76, 93, 82, 89])>

### (3) tf.transpose
Tensor의 축의 순서를 바꾸어 줍니다. 이는 **원소의 순서를 바꾸는 행위**로, reshape와는 전혀 다른 동작입니다.

In [19]:
# 축 : (기간, 학생, 성적)  -> (학생, 기간, 성적)
tf.transpose(scores_tensor,[1,0,2]).numpy()

array([[[80, 92, 70, 65, 92],
        [85, 95, 90, 66, 93]],

       [[91, 75, 90, 68, 85],
        [93, 70, 80, 60, 81]],

       [[86, 76, 42, 72, 88],
        [89, 78, 55, 75, 80]],

       [[77, 92, 52, 60, 80],
        [80, 94, 59, 72, 90]],

       [[75, 85, 85, 92, 95],
        [70, 82, 81, 95, 72]],

       [[96, 90, 95, 81, 72],
        [90, 76, 93, 82, 89]]])

In [20]:
# 축 : (기간, 학생, 성적)  -> (학생, 성적, 기간)
tf.transpose(scores_tensor,[1,2,0]).numpy()

array([[[80, 85],
        [92, 95],
        [70, 90],
        [65, 66],
        [92, 93]],

       [[91, 93],
        [75, 70],
        [90, 80],
        [68, 60],
        [85, 81]],

       [[86, 89],
        [76, 78],
        [42, 55],
        [72, 75],
        [88, 80]],

       [[77, 80],
        [92, 94],
        [52, 59],
        [60, 72],
        [80, 90]],

       [[75, 70],
        [85, 82],
        [85, 81],
        [92, 95],
        [95, 72]],

       [[96, 90],
        [90, 76],
        [95, 93],
        [81, 82],
        [72, 89]]])

`transpose`는 현재 배열 내 원소들의 순서를 바꾸어줍니다. reshape의 동작과 헷갈리면, 나중에 코드를 작성할 때, 많은 오류들이 발생하게 됩니다.

In [21]:
# reshape는 바꾼 후 다시 돌려놓아도 동일합니다.
reshaped_tensor = tf.reshape(scores_tensor,[-1])
tf.reshape(reshaped_tensor,[2,6,5]).numpy()

array([[[80, 92, 70, 65, 92],
        [91, 75, 90, 68, 85],
        [86, 76, 42, 72, 88],
        [77, 92, 52, 60, 80],
        [75, 85, 85, 92, 95],
        [96, 90, 95, 81, 72]],

       [[85, 95, 90, 66, 93],
        [93, 70, 80, 60, 81],
        [89, 78, 55, 75, 80],
        [80, 94, 59, 72, 90],
        [70, 82, 81, 95, 72],
        [90, 76, 93, 82, 89]]])

In [22]:
# transpose는 바꾼 후 reshape하면 값의 순서가 바뀌어져 있습니다.
transposed_tensor = tf.transpose(scores_tensor,[1,2,0])
tf.reshape(transposed_tensor,[2,6,5]).numpy()

array([[[80, 85, 92, 95, 70],
        [90, 65, 66, 92, 93],
        [91, 93, 75, 70, 90],
        [80, 68, 60, 85, 81],
        [86, 89, 76, 78, 42],
        [55, 72, 75, 88, 80]],

       [[77, 80, 92, 94, 52],
        [59, 60, 72, 80, 90],
        [75, 70, 85, 82, 85],
        [81, 92, 95, 95, 72],
        [96, 90, 90, 76, 95],
        [93, 81, 82, 72, 89]]])

In [23]:
# 아래와 같이 해야 다시 돌아옵니다.
transposed_tensor = tf.transpose(scores_tensor,[1,2,0])
tf.transpose(transposed_tensor,[2,0,1]).numpy()

array([[[80, 92, 70, 65, 92],
        [91, 75, 90, 68, 85],
        [86, 76, 42, 72, 88],
        [77, 92, 52, 60, 80],
        [75, 85, 85, 92, 95],
        [96, 90, 95, 81, 72]],

       [[85, 95, 90, 66, 93],
        [93, 70, 80, 60, 81],
        [89, 78, 55, 75, 80],
        [80, 94, 59, 72, 90],
        [70, 82, 81, 95, 72],
        [90, 76, 93, 82, 89]]])

#### 예제) 중간고사 때의 수학 성적과 기말고사 때의 과학 성적 가져오기

tf.transpose와 tf.gather_nd를 같이 이용하면 가능합니다.

In [24]:
transposed_tensor = tf.transpose(scores_tensor,[0,2,1])
transposed_tensor

<tf.Tensor: id=69, shape=(2, 5, 6), dtype=int64, numpy=
array([[[80, 91, 86, 77, 75, 96],
        [92, 75, 76, 92, 85, 90],
        [70, 90, 42, 52, 85, 95],
        [65, 68, 72, 60, 92, 81],
        [92, 85, 88, 80, 95, 72]],

       [[85, 93, 89, 80, 70, 90],
        [95, 70, 78, 94, 82, 76],
        [90, 80, 55, 59, 81, 93],
        [66, 60, 75, 72, 95, 82],
        [93, 81, 80, 90, 72, 89]]])>

In [25]:
tf.gather_nd(transposed_tensor,[[0,2],[1,4]])

<tf.Tensor: id=72, shape=(2, 6), dtype=int64, numpy=
array([[70, 90, 42, 52, 85, 95],
       [93, 81, 80, 90, 72, 89]])>

## 3. 텐서를 합치고 쪼개는 메소드들 

---

+ 서로 다른 두 텐서를 합치고, 쪼개는 방식에 대해 배워보겠습니다.

### (1) tf.stack
Tensor을 특정 축의 방향에 따라 쌓기 위해서는 `tf.stack`을 이용하면 됩니다.

In [26]:
middle_tensor = scores_tensor[0]
final_tensor = scores_tensor[1]

In [27]:
# 0차원 축으로 쌓기
tf.stack([middle_tensor,final_tensor]).numpy()

array([[[80, 92, 70, 65, 92],
        [91, 75, 90, 68, 85],
        [86, 76, 42, 72, 88],
        [77, 92, 52, 60, 80],
        [75, 85, 85, 92, 95],
        [96, 90, 95, 81, 72]],

       [[85, 95, 90, 66, 93],
        [93, 70, 80, 60, 81],
        [89, 78, 55, 75, 80],
        [80, 94, 59, 72, 90],
        [70, 82, 81, 95, 72],
        [90, 76, 93, 82, 89]]])

In [28]:
# 1차원 축으로 쌓기
tf.stack([middle_tensor,final_tensor],axis=1).numpy()

array([[[80, 92, 70, 65, 92],
        [85, 95, 90, 66, 93]],

       [[91, 75, 90, 68, 85],
        [93, 70, 80, 60, 81]],

       [[86, 76, 42, 72, 88],
        [89, 78, 55, 75, 80]],

       [[77, 92, 52, 60, 80],
        [80, 94, 59, 72, 90]],

       [[75, 85, 85, 92, 95],
        [70, 82, 81, 95, 72]],

       [[96, 90, 95, 81, 72],
        [90, 76, 93, 82, 89]]])

In [29]:
# 2차원 축으로 쌓기
tf.stack([middle_tensor,final_tensor],axis=2).numpy()

array([[[80, 85],
        [92, 95],
        [70, 90],
        [65, 66],
        [92, 93]],

       [[91, 93],
        [75, 70],
        [90, 80],
        [68, 60],
        [85, 81]],

       [[86, 89],
        [76, 78],
        [42, 55],
        [72, 75],
        [88, 80]],

       [[77, 80],
        [92, 94],
        [52, 59],
        [60, 72],
        [80, 90]],

       [[75, 70],
        [85, 82],
        [85, 81],
        [92, 95],
        [95, 72]],

       [[96, 90],
        [90, 76],
        [95, 93],
        [81, 82],
        [72, 89]]])

### (2) tf.unstack
Tensor을 특정 축의 방향에 따라 쪼개기 위해서는 `tf.unstack`을 이용하면 됩니다.

In [30]:
# 중간 / 기말로 쪼개기
tf.unstack(scores_tensor)

[<tf.Tensor: id=88, shape=(6, 5), dtype=int64, numpy=
 array([[80, 92, 70, 65, 92],
        [91, 75, 90, 68, 85],
        [86, 76, 42, 72, 88],
        [77, 92, 52, 60, 80],
        [75, 85, 85, 92, 95],
        [96, 90, 95, 81, 72]])>,
 <tf.Tensor: id=89, shape=(6, 5), dtype=int64, numpy=
 array([[85, 95, 90, 66, 93],
        [93, 70, 80, 60, 81],
        [89, 78, 55, 75, 80],
        [80, 94, 59, 72, 90],
        [70, 82, 81, 95, 72],
        [90, 76, 93, 82, 89]])>]

In [31]:
# 학생 별로 쪼개기
tf.unstack(scores_tensor,axis=1)

[<tf.Tensor: id=92, shape=(2, 5), dtype=int64, numpy=
 array([[80, 92, 70, 65, 92],
        [85, 95, 90, 66, 93]])>,
 <tf.Tensor: id=93, shape=(2, 5), dtype=int64, numpy=
 array([[91, 75, 90, 68, 85],
        [93, 70, 80, 60, 81]])>,
 <tf.Tensor: id=94, shape=(2, 5), dtype=int64, numpy=
 array([[86, 76, 42, 72, 88],
        [89, 78, 55, 75, 80]])>,
 <tf.Tensor: id=95, shape=(2, 5), dtype=int64, numpy=
 array([[77, 92, 52, 60, 80],
        [80, 94, 59, 72, 90]])>,
 <tf.Tensor: id=96, shape=(2, 5), dtype=int64, numpy=
 array([[75, 85, 85, 92, 95],
        [70, 82, 81, 95, 72]])>,
 <tf.Tensor: id=97, shape=(2, 5), dtype=int64, numpy=
 array([[96, 90, 95, 81, 72],
        [90, 76, 93, 82, 89]])>]

In [32]:
# 과목 별로 쪼개기
tf.unstack(scores_tensor,axis=2)

[<tf.Tensor: id=104, shape=(2, 6), dtype=int64, numpy=
 array([[80, 91, 86, 77, 75, 96],
        [85, 93, 89, 80, 70, 90]])>,
 <tf.Tensor: id=105, shape=(2, 6), dtype=int64, numpy=
 array([[92, 75, 76, 92, 85, 90],
        [95, 70, 78, 94, 82, 76]])>,
 <tf.Tensor: id=106, shape=(2, 6), dtype=int64, numpy=
 array([[70, 90, 42, 52, 85, 95],
        [90, 80, 55, 59, 81, 93]])>,
 <tf.Tensor: id=107, shape=(2, 6), dtype=int64, numpy=
 array([[65, 68, 72, 60, 92, 81],
        [66, 60, 75, 72, 95, 82]])>,
 <tf.Tensor: id=108, shape=(2, 6), dtype=int64, numpy=
 array([[92, 85, 88, 80, 95, 72],
        [93, 81, 80, 90, 72, 89]])>]

### (3) tf.concat
Tensor을 특정 축의 방향에 따라 합치기 위해서는 `tf.concat`을 이용하면 됩니다.

In [33]:
# 0번째 축으로 쌓기
middle_tensor = scores_tensor[0]
final_tensor = scores_tensor[1]

tf.concat([middle_tensor,final_tensor],axis=0)

<tf.Tensor: id=123, shape=(12, 5), dtype=int64, numpy=
array([[80, 92, 70, 65, 92],
       [91, 75, 90, 68, 85],
       [86, 76, 42, 72, 88],
       [77, 92, 52, 60, 80],
       [75, 85, 85, 92, 95],
       [96, 90, 95, 81, 72],
       [85, 95, 90, 66, 93],
       [93, 70, 80, 60, 81],
       [89, 78, 55, 75, 80],
       [80, 94, 59, 72, 90],
       [70, 82, 81, 95, 72],
       [90, 76, 93, 82, 89]])>

In [34]:
# 1번째 축으로 쌓기
middle_tensor = scores_tensor[0]
final_tensor = scores_tensor[1]

tf.concat([middle_tensor,final_tensor],axis=1)

<tf.Tensor: id=134, shape=(6, 10), dtype=int64, numpy=
array([[80, 92, 70, 65, 92, 85, 95, 90, 66, 93],
       [91, 75, 90, 68, 85, 93, 70, 80, 60, 81],
       [86, 76, 42, 72, 88, 89, 78, 55, 75, 80],
       [77, 92, 52, 60, 80, 80, 94, 59, 72, 90],
       [75, 85, 85, 92, 95, 70, 82, 81, 95, 72],
       [96, 90, 95, 81, 72, 90, 76, 93, 82, 89]])>

## 4. 텐서를 생성하는 메소드들 

---

+ 원하는 형태의 텐서를 생성하는 여러가지 메소드들에 대해 배워보겠습니다.

### (1) tf.ones & tf.ones_like
원소의 값이 1인 Tensor을 만들기 위한 메소드들입니다.

In [35]:
# shape을 지정
tf.ones([3,3]).numpy()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [36]:
# 해당 텐서와 같은 크기의 ones 행렬 만들기
tf.ones_like(scores_tensor).numpy()

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [37]:
# ones_like는 이것과 동일합니다.
score_shape = tf.shape(scores_tensor)
tf.ones(score_shape).numpy()

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)

### (2) tf.tile
tensor을 각 축 방향으로 tile처럼 복사하는 메소드입니다.

In [38]:
nums_tensor = tf.constant([[0,1,2],[2,3,4]])
nums_tensor

<tf.Tensor: id=148, shape=(2, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [2, 3, 4]], dtype=int32)>

In [39]:
tf.tile(nums_tensor,[1,1])

<tf.Tensor: id=151, shape=(2, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [2, 3, 4]], dtype=int32)>

In [40]:
tf.tile(nums_tensor,[2,1])

<tf.Tensor: id=154, shape=(4, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [2, 3, 4],
       [0, 1, 2],
       [2, 3, 4]], dtype=int32)>

In [41]:
tf.tile(nums_tensor,[1,3])

<tf.Tensor: id=157, shape=(2, 9), dtype=int32, numpy=
array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [2, 3, 4, 2, 3, 4, 2, 3, 4]], dtype=int32)>

In [42]:
tf.tile(nums_tensor,[2,3])

<tf.Tensor: id=160, shape=(4, 9), dtype=int32, numpy=
array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [2, 3, 4, 2, 3, 4, 2, 3, 4],
       [0, 1, 2, 0, 1, 2, 0, 1, 2],
       [2, 3, 4, 2, 3, 4, 2, 3, 4]], dtype=int32)>

### (3) tf.meshgrid
meshgrid는 직교 좌표계(cartesian coordinates)를 만들어주는 메소드입니다.

In [43]:
tf.meshgrid([1,2,3],[2,3,4])

[<tf.Tensor: id=187, shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]], dtype=int32)>,
 <tf.Tensor: id=188, shape=(3, 3), dtype=int32, numpy=
 array([[2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]], dtype=int32)>]

In [44]:
# meshgrid는 주로 stack과 같이 이용합니다. 
xs, ys = tf.meshgrid([1,2,3],[2,3,4])
tf.stack([xs,ys],axis=-1)

<tf.Tensor: id=218, shape=(3, 3, 2), dtype=int32, numpy=
array([[[1, 2],
        [2, 2],
        [3, 2]],

       [[1, 3],
        [2, 3],
        [3, 3]],

       [[1, 4],
        [2, 4],
        [3, 4]]], dtype=int32)>

#  

---

    Copyright(c) 2019 by Public AI. All rights reserved.
    Writen by PAI, SangJae Kang ( rocketgrowthsj@publicai.co.kr )  last updated on 2019/03/22


---