 ╔══<i><b>Alai-DeepLearning</b></i>═══════════════════════════╗
###  &nbsp;&nbsp; **✎&nbsp;&nbsp;week 4. Tensorflow basis**
# Section 4. Tensor을 연산하는 함수들

### _Objective_
1. 텐서를 연산하는 다양한 메소드에 대해 배워봅니다. <br>
2. 텐서를 정렬하는 메소드에 대해 배워봅니다. <br>
3. 이 외 필수적으로 알고 있어야 하는 다양한 메소드에 대해 배워봅니다.

╚════════════════════════════════════════╝

In [3]:
%matplotlib inline
import numpy as np
import tensorflow as tf 
import matplotlib.pyplot as plt

### [Optional.  eager_execution 이용하기 ]

---

> _`tensorflow` 2.0 버전부터 지원하게 된 기능으로, graph와 session을 따로 만들어서 실행하지 않고, **즉시 실행**가능하도록 만든 기능입니다._<br>
> _이번 실습시간에서는 eager execution으로 실습을 진행하겠습니다. <br>

In [4]:
# Tensorflow
tf.enable_eager_execution()

In [5]:
# eager execution은 아래와 같이 나옵니다.
a = tf.constant(1)
b = tf.constant(2)
tf.add(a,b)
b**2

<tf.Tensor: id=4, shape=(), dtype=int32, numpy=4>

## 예제 데이터 )  학생들의 국영수사과 성적표


#### 데이터 1) 중간고사, 학생들의 국영수사과 성적표
`middle_scores`

| 학생 번호 | 국어 | 영어 | 수학 | 사회 | 과학 |
|  ----   | --- |---| --- | --- | --- |
|0 |80 |92 |70 | 65 | 92 |
|1 |91 |75 |90 | 68 | 85 | 
|2 |86 |76 |42 | 72 | 88 |
|3 |77 |92 |52 | 60 | 80 |
|4 |75 |85 |85 | 92 | 95 |
|5 |96 |90 |95 | 81 | 72 |

#### 데이터 2) 기말고사, 학생들의 국영수사과 성적표
`final_scores`

| 학생 번호 | 국어 | 영어 | 수학 | 사회 | 과학 |
|  ----   | --- |---| --- | --- | --- |
|0 |85 |95 |90 | 66 | 93 |
|1 |93 |70 |80 | 60 | 81 | 
|2 |89 |78 |55 | 75 | 80 |
|3 |80 |94 |59 | 72 | 90 |
|4 |70 |82 |81 | 95 | 72 |
|5 |90 |76 |93 | 82 | 89 |

In [6]:
middle_scores = np.array([
    [80,92,70,65,92],
    [91,75,90,68,85],
    [86,76,42,72,88],
    [77,92,52,60,80],
    [75,85,85,92,95],
    [96,90,95,81,72]
])

final_scores = np.array([
    [85,95,90,66,93],
    [93,70,80,60,81],
    [89,78,55,75,80],
    [80,94,59,72,90],
    [70,82,81,95,72],
    [90,76,93,82,89]
])

# Numpy array
scores = np.stack([middle_scores,final_scores])

# Tensor로 만들기
scores_tensor = tf.constant(scores)

scores_tensor.numpy()

array([[[80, 92, 70, 65, 92],
        [91, 75, 90, 68, 85],
        [86, 76, 42, 72, 88],
        [77, 92, 52, 60, 80],
        [75, 85, 85, 92, 95],
        [96, 90, 95, 81, 72]],

       [[85, 95, 90, 66, 93],
        [93, 70, 80, 60, 81],
        [89, 78, 55, 75, 80],
        [80, 94, 59, 72, 90],
        [70, 82, 81, 95, 72],
        [90, 76, 93, 82, 89]]])

# \[1. 축 연산(axis) \]

---

---

> Tensorflow에서는 축을 기준으로 연산하는 메소드들을 `reduce_*`의 이름으로 존재합니다.

### (1) tf.reduce_mean  

`numpy.mean`과 유사한 API를 가지고 있습니다. 

In [7]:
# 전체 평균 구하기
tf.math.reduce_mean(scores_tensor).numpy()

80

In [8]:
# 학생 별, 과목 별 평균
# (2,6,5)-> (6,5)
tf.math.reduce_mean(scores_tensor,axis=[0]).numpy()

array([[82, 93, 80, 65, 92],
       [92, 72, 85, 64, 83],
       [87, 77, 48, 73, 84],
       [78, 93, 55, 66, 85],
       [72, 83, 83, 93, 83],
       [93, 83, 94, 81, 80]])

In [9]:
# 기간 별, 과목 별 평균
# (2,6,5)-> (2,5)
tf.math.reduce_mean(scores_tensor,axis=[1]).numpy()

array([[84, 85, 72, 73, 85],
       [84, 82, 76, 75, 84]])

In [10]:
# 학생 별 평균
tf.math.reduce_mean(scores_tensor,axis=[0,2]).numpy()

array([82, 79, 74, 75, 83, 86])

_`numpy.array`는 복수개의 방향으로 연산이 일어나지 못하지만, `Tensorflow`에서는 가능합니다._

### (2) 이 외 다른 reduce 연산들

* `mean`이 외에도 `reduce_sum`,`reduce_min`,`reduce_max`,`reduce_std` 등이 존재합니다.

In [11]:
# 학생 별 성적 총합
tf.math.reduce_sum(scores_tensor,axis=[0,2]).numpy()

array([828, 793, 741, 756, 832, 864])

In [12]:
# 과목 별 최저 점수
tf.math.reduce_min(scores_tensor,axis=[0,1]).numpy()

array([70, 70, 42, 60, 72])

In [13]:
# 과목 별 최저 점수
tf.math.reduce_max(scores_tensor,axis=[0,1]).numpy()

array([96, 95, 95, 95, 95])

### (3) map_fn 연산

---

+ map_fn이란, 0번째 축 방향으로 일괄적으로 함수를 적용하는 메소드입니다.

기간, 과목 별로 학생 최고점과 최저점의 차이를 구해봅시다.

In [14]:
def calculate_min_max(tensor):
    max_value = tf.reduce_max(tensor,axis=1)
    min_value = tf.reduce_min(tensor,axis=1)
    return max_value - min_value

In [15]:
tf.map_fn(calculate_min_max, scores_tensor)

<tf.Tensor: id=73, shape=(2, 6), dtype=int64, numpy=
array([[27, 23, 46, 40, 20, 24],
       [29, 33, 34, 35, 25, 17]])>

# \[ 2. 논리 연산 \]

---

---

> Tensorflow에서는 python의 and,or,not과 같은 논리 연산하는 메소드들을 `logical_*`의 이름으로 존재합니다.

### (1) logical_and

원소 별로 둘다 만족하는 것을 확인합니다.

In [16]:
middle_tensor = scores_tensor[0]
final_tensor = scores_tensor[1]

In [17]:
over_80 = tf.math.logical_and((middle_tensor>80),
                              (final_tensor>80))

In [18]:
over_80.numpy()

array([[False,  True, False, False,  True],
       [ True, False, False, False,  True],
       [ True, False, False, False, False],
       [False,  True, False, False, False],
       [False,  True,  True,  True, False],
       [ True, False,  True,  True, False]])

위는 `&`연산으로 가능합니다.

In [19]:
(middle_tensor>80) & (final_tensor>80)

<tf.Tensor: id=93, shape=(6, 5), dtype=bool, numpy=
array([[False,  True, False, False,  True],
       [ True, False, False, False,  True],
       [ True, False, False, False, False],
       [False,  True, False, False, False],
       [False,  True,  True,  True, False],
       [ True, False,  True,  True, False]])>

### (2) logical_or
원소 별로 둘 중 하나라도 만족하는 것을 확인합니다.

In [20]:
over_80 = tf.math.logical_or((middle_tensor>80),
                             (final_tensor>80))
over_80.numpy()

array([[ True,  True,  True, False,  True],
       [ True, False,  True, False,  True],
       [ True, False, False, False,  True],
       [False,  True, False, False,  True],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

위는 `|`연산으로 가능합니다.

In [21]:
(middle_tensor>80) | (final_tensor>80)

<tf.Tensor: id=105, shape=(6, 5), dtype=bool, numpy=
array([[ True,  True,  True, False,  True],
       [ True, False,  True, False,  True],
       [ True, False, False, False,  True],
       [False,  True, False, False,  True],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])>

### (3) logical_not
elementwise로 결과를 반전시킵니다.

In [22]:
tf.math.logical_not(middle_tensor>80)

<tf.Tensor: id=109, shape=(6, 5), dtype=bool, numpy=
array([[ True, False,  True,  True, False],
       [False,  True, False,  True, False],
       [False,  True,  True,  True, False],
       [ True, False,  True,  True,  True],
       [ True, False, False, False, False],
       [False, False, False, False,  True]])>

위는 `~`연산으로 가능합니다.

In [23]:
~(middle_tensor>80)

<tf.Tensor: id=113, shape=(6, 5), dtype=bool, numpy=
array([[ True, False,  True,  True, False],
       [False,  True, False,  True, False],
       [False,  True,  True,  True, False],
       [ True, False,  True,  True,  True],
       [ True, False, False, False, False],
       [False, False, False, False,  True]])>

### (4) logical_xor
원소 별로 xor관계인 결과를 반환합니다.

In [24]:
over_80 = tf.math.logical_xor((middle_tensor>80),
                             (final_tensor>80))
over_80.numpy()

array([[ True, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False, False, False,  True],
       [False, False, False, False,  True],
       [False, False, False, False,  True],
       [False,  True, False, False,  True]])

위는 `^`연산으로 가능합니다.

In [25]:
(middle_tensor>80) ^ (final_tensor>80)

<tf.Tensor: id=131, shape=(6, 5), dtype=bool, numpy=
array([[ True, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False, False, False,  True],
       [False, False, False, False,  True],
       [False, False, False, False,  True],
       [False,  True, False, False,  True]])>

# \[ 3. 형 변환 연산 \]

---

---

> 텐서플로우는 numpy와 다르게 엄격히 자료형(datatype)을 관리합니다. 이를 변환시키는 메소드로 `tf.cast`가 있습니다.

In [26]:
middle_tensor = scores_tensor[0]

# 80점 이상 True
mask = middle_tensor > 80

mask * middle_tensor

InvalidArgumentError: cannot compute Mul as input #0(zero-based) was expected to be a int64 tensor but is a bool tensor [Op:Mul] name: mul/

아래와 같이, mask의 형을 변환시키면 가능합니다.

In [ ]:
int_mask = tf.cast(mask, tf.int64)
int_mask * middle_tensor

# \[ 4. 조건 연산 \]

---

---

> 조건에 따라 서로 다른 연산을 하는 경우가 있습니다. 다음에 배울 예정인 `dropout`과 같이, Test일때와, Train 일때 서로 다른 결과를 반환해야 하는 경우가 있습니다.

In [27]:
def dropout_value(value_tensor):
    dropout_mask = tf.cast(
        tf.random.uniform(value_tensor.shape,0,1)>0.5,tf.float32)
    return dropout_mask * value_tensor

### (1) 참인 경우의 동작

In [32]:
is_training = tf.constant(True)

value_tensor = tf.constant([1,2,3,4,5,6,7,8,9,10],tf.float32)

tf.cond(is_training, 
        lambda : dropout_value(value_tensor), 
        lambda : value_tensor).numpy()

array([1., 0., 0., 0., 0., 6., 0., 0., 9., 0.], dtype=float32)

### (2) 거짓인 경우의 동작

In [35]:
is_training = tf.constant(False)

value_tensor = tf.constant([1,2,3,4,5,6,7,8,9,10],tf.float32)

tf.cond(is_training, 
        lambda : dropout_value(value_tensor), 
        lambda : value_tensor).numpy()

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

*이 때 중요한 것은 tf.cond에 들어가는 `true_fn`과 `false_fn`에는 인수가 없는, 호출가능한 함수가 들어가야 합니다.*

# \[ 5. 정렬 연산 \]

---

---

> Tensorflow에서는 1.13버전 이후 공식적으로 `tf.argsort`와 `tf.sort`를 지원해주기 시작했습니다. 이전까지는 텐서플로우에는 정렬에 대한 함수가 존재하지 않아, 사람들이 직접구현하거나, 복잡한 API를 통해 이용했습니다. 


### (1) argsort

텐서를 정렬한 순서에 맞게 인덱스를 반환하는 메소드입니다.

In [27]:
middle_tensor = scores_tensor[0]
middle_tensor

<tf.Tensor: id=149, shape=(6, 5), dtype=int64, numpy=
array([[80, 92, 70, 65, 92],
       [91, 75, 90, 68, 85],
       [86, 76, 42, 72, 88],
       [77, 92, 52, 60, 80],
       [75, 85, 85, 92, 95],
       [96, 90, 95, 81, 72]])>

In [28]:
tf.argsort(middle_tensor,axis=0) # 오름차순 정렬

<tf.Tensor: id=164, shape=(6, 5), dtype=int32, numpy=
array([[4, 1, 2, 3, 5],
       [3, 2, 3, 0, 3],
       [0, 4, 0, 1, 1],
       [2, 5, 4, 2, 2],
       [1, 0, 1, 5, 0],
       [5, 3, 5, 4, 4]], dtype=int32)>

In [29]:
tf.argsort(middle_tensor,axis=0,direction='DESCENDING') # 내림차순 정렬

<tf.Tensor: id=178, shape=(6, 5), dtype=int32, numpy=
array([[5, 0, 5, 4, 4],
       [1, 3, 1, 5, 0],
       [2, 5, 4, 2, 2],
       [0, 4, 0, 1, 1],
       [3, 2, 3, 0, 3],
       [4, 1, 2, 3, 5]], dtype=int32)>

### (2) sort

텐서를 순서에 맞게 정렬하는 메소드입니다.

In [30]:
middle_tensor = scores_tensor[0]
middle_tensor

<tf.Tensor: id=183, shape=(6, 5), dtype=int64, numpy=
array([[80, 92, 70, 65, 92],
       [91, 75, 90, 68, 85],
       [86, 76, 42, 72, 88],
       [77, 92, 52, 60, 80],
       [75, 85, 85, 92, 95],
       [96, 90, 95, 81, 72]])>

In [31]:
tf.sort(middle_tensor,axis=0) # 오름차순 정렬

<tf.Tensor: id=199, shape=(6, 5), dtype=int64, numpy=
array([[75, 75, 42, 60, 72],
       [77, 76, 52, 65, 80],
       [80, 85, 70, 68, 85],
       [86, 90, 85, 72, 88],
       [91, 92, 90, 81, 92],
       [96, 92, 95, 92, 95]])>

In [32]:
tf.sort(middle_tensor,axis=0,direction='DESCENDING') # 내림차순 정렬

<tf.Tensor: id=213, shape=(6, 5), dtype=int64, numpy=
array([[96, 92, 95, 92, 95],
       [91, 92, 90, 81, 92],
       [86, 90, 85, 72, 88],
       [80, 85, 70, 68, 85],
       [77, 76, 52, 65, 80],
       [75, 75, 42, 60, 72]])>

#  

---

    Copyright(c) 2019 by Public AI. All rights reserved.
    Writen by PAI, SangJae Kang ( rocketgrowthsj@publicai.co.kr )  last updated on 2019/03/22


---